"""KHOA 포털 관측소 목록과 해수욕장 번들 데이터.

KHOA ODMI 서비스는 보통 data.go.kr 엔드포인트로 제공되지만, 포털 상세
페이지의 관측소 목록은 별도 AJAX 엔드포인트에 들어 있습니다. 이 모듈은 그
비표준 엔드포인트를 감싸고, "해수욕장 정보" 상세 페이지의 관측소 목록을
번들 데이터로 제공합니다.
"""

from __future__ import annotations

import base64
import importlib
import json
import math
import re
import zlib
from collections.abc import Mapping
from os import PathLike
from typing import Any, Final, Protocol, cast

import requests

from .exceptions import KhoaParseError, KhoaRequestError, KhoaServerError
from .models import Observatory

KHOA_OPENAPI_INFO_URL: Final = "https://www.khoa.go.kr/oceandata/openapi/getOpenApiInfo.do"
KHOA_OPENAPI_DETAIL_URL: Final = "https://www.khoa.go.kr/oceandata/openapi/openApiDetail.do"

BEACH_OPENAPI_ID: Final = "36"
BEACH_INFO_TITLE: Final = "해수욕장 정보"
BEACH_INFO_MODIFY_CYCLE: Final = "상시"
BEACH_INFO_UPDATE_INTERVAL_MINUTES: Final = 30
BEACH_OBSERVATORY_SOURCE_DATE: Final = "2026-05-10"
BEACH_OBSERVATORY_SOURCE_SHA256: Final = (
    "9b64b14215052a79ae5736b4f13ae9733e520e5e410055b10e28b91506ceb3c7"
)
DEFAULT_ADDRESS_SEARCH_OFFSETS_DEGREES: Final = (
    0.0,
    0.0005,
    0.001,
    0.002,
    0.003,
    0.005,
    0.008,
    0.01,
    0.015,
    0.02,
)
_ROAD_BUILDING_NUMBER_RE: Final = re.compile(
    r"(?<!\d)(\d{1,5})(?:-(\d{1,5}))?(?=\s*(?:\(|$))"
)


class PortalResponseLike(Protocol):
    """KHOA 포털 AJAX 호출에 필요한 최소 응답 프로토콜."""

    status_code: int
    text: str
    content: bytes

    def json(self) -> Any: ...


class PortalSessionLike(Protocol):
    """KHOA 포털 AJAX 호출에 필요한 최소 세션 프로토콜."""

    def post(
        self,
        url: str,
        *,
        data: Mapping[str, Any],
        headers: Mapping[str, str],
        timeout: float,
    ) -> PortalResponseLike: ...


class VworldReverseGeocoderLike(Protocol):
    """VWorld 역지오코딩 클라이언트에 필요한 최소 프로토콜."""

    def reverse_geocode_latlon(self, lat: float, lon: float, **kwargs: Any) -> Mapping[str, Any]:
        """WGS84 위도/경도 좌표를 VWorld 주소 응답으로 변환합니다."""

        ...


_BEACH_OBSERVATORIES_ZLIB_B64: Final = (
    "eJztvV1vHEmaLvZXCF1pAFUi4zMz5+7sgYFz4ytfGsagPTNYLzA7s5idY/vYOABFUVp2izKlHVWrKJE65EpqSg0KUy1RampB2f+n"
    "Mus/GO8bkZkRyXizMopVNcc+2wvMstXJUHzH+/G8z/M//p+3/u43t35562/+/X9gLL1159bvv/n739765S2R355dTqud8/L88hfz"
    "8UW1N6mej6uXb27dufWbb/70za/+9J/+Ab77m//u3/37/3Drzq3fffOnW78UeZKm6s6t3/3h97d+yXieZILdufW73/7tN7/71W/+"
    "8Pu//dWv//Ab+CXFcpEKkXJ2686tf/jmj7/+7e9+9c1vfvPH3/7jP9765a3ZdFy9eDz/7kv5cbd6+bj6MikPdreq759U3z+ZfZpu"
    "zSe75ee75buLrerl09mnx+UP51uSjYpbd27ZRn71u2/+9Hd/+o/wd9Vdav7LH37/t/Y/NR2s/9tv/u4f//TN73/921/9/a1fpkna"
    "/oe//+ZPv/5f6hH/9n//5td/cv6uf/zDf/zjr+E//K//2x/++Lvf3PrPd9op5Vy3Uzqbbs8+7g6eS5lIIZu51IlQMjSXUhdpKngq"
    "gnNZneyWx1flzlucwrPd8mAXpnD28WT2aQpTOLvcm33chSlkSoz4rTu3/viHb34T00L18KT8slsdT8rp0/Lhz7PLyy0tt26bT2G0"
    "3z+p7h3P7x3NLrZ/cevOrf/j7/6h3gZ5waDXv/ntn775O6/Xod8NL6+dpeDywpwJFV5fqZJcaWKJf//bb/74P/+nnjX2Z6m7FDJL"
    "Bctlmqapxv9N61+AneB9bT/1N40U3qYpz/bKv1wO3jcqEUXu7BuZ5uF9k2cpV5qLxftmcnd2YY7e4aPywaPq+NEWbJqzPdg3WVGM"
    "8kX7JtRCPbLy9GhLiGLEuL87MjNxgUW3QyQWHQe82jNNrbeZQsGLPE15mqZCFGma4kAC651nqf3UX2/mXxLVznnEJSEyZ60LTq11"
    "kQqZcrV4rQ/rE16Nv1Y7eMLn44vy4BDWuhAS74jgQYSeEEtS8KznHBZs2XPoTmNacH8az4bftXkiMuG8WyotiHeLwwEPn5nwuzX7"
    "eFLt/oQT+uprdTjGSxd7h5eut+W5zKS8fpRiG4YrGLt4/WJ9dTW/d0w9lDgHxEOJM7KJQ1XPsVQpF1rD7ckFeYni1/ZT/1Bp5u6G"
    "vep4vzq+GLwhdKIL7RwspnjwYMmcKzBksuDB+vyu+vDeHqz5vaNqvIdP589X8+M3+HSejKtXX2EfVDvTLSazkdThxbH9IY4X9m59"
    "VoziuTuXj6vPT+FK+LjdO4VZolhrvxQJ4zp8pliWslTi+g48U+XBIazkw6Ot6vm76mRcHhyaGeQjNvT4OG1c7FUvHnM4NWrrdtPi"
    "nfLD0+rVVTXene/vz7+79G0XrrI8DR2xzm9t8VSVB4fhVbVTFFxVO2GbOXIsSxVPpdRwueFhUz1HjmX1p942Yb6xOy7PhxstWZIV"
    "7WbJk4IFHzLFmEoZEzGbBXryw7ew0KZPsFmYecbc5ZQ6G3zzNi1W069wEsCA0WyUZVu3m7/jF9SS40CJWxaHvaElV6nKU8F5mkq4"
    "X4VmaZpmGbHkqv7UX3Lm3Qx/Kc/2quPhz26WFNJzF/Med1GmIl/WXdx5C9dtufO2Gp/Adau0HjExdL2DbZ29LqdPqyN8bFkhR2jE"
    "uRsqVRm1BXDUlEcKc7ChhxZnVapUpToHu7UAbwUHEnpoRf2p/9Cm7kP70xR3f4yXm/JmB2SJSAknl4lU6JTzxQbss3P4m+Fw7lxZ"
    "A7Z8NK4u9mHhBSfNV+hHcE1sr9b3vqaFE3iZ/TStznYZK38Y7gXkiZTu7SmVIs1XrkRM2KW1Mk3H0HPDn2A6uXlwPQt2+Lki2p7f"
    "24XmT4+2imykg2bs9Ovs4wllxuJcEKcLZ2ZjZizYhlzINEUDtgCHNqVOFxi9+Km/NfLi2taI3Rmtg5gnUm9wZxRr3Bqcy2V2Rmbs"
    "GmPi0LtEy/Y7wrTO0kSzYrUBpOubhnM6gERuGi7dTfPh3fxg+IZRiW4dYZ1IHXaEeZ7238ef714zuD9vWweo/LhtL2bTudoBklnI"
    "fB/emvnJuCa4R0xgygkpaSGIRxnGnQ7YHDglxB2SsUTLFccU65kW+P/xBuEQY0rz4JbAr8ynvqGmXUPtw9fqZBzhC8u8faOLRAoR"
    "fKOzLEuFSkU4OPLha3XvLsTtTTiwfDTG0MXncbMVoFMYy+cy6MYNawH9OFZ03iWhJfXy2+ERTpgUnIpcySRLxYojyGYOlcyUFDl6"
    "YgxXmwUjivC1/dR/NTAZ0K42nLH97QizPIeBOc7YOn0xOPmK3cT3kkJ1HC/fsSOiyHaYpCv21/LEpOh1vsOemPDu/I/gpkSsN1OF"
    "c+nzLAstOM8zDlcQcekfX1YfjmYXT6pn73F5Jl8gFAkn9OXj6sVTjHcdX1Qvn6AdLsVIUMvCVEFfv9i50MIolagiW0kkWbqX5ceT"
    "8uWk/Lw3IOSlE+WkXopEBg+OOeQZ5c6Gr7ny45PZx1PzyuFP4MXmIzX4nuw2wOCeLHTXbxVappK6KHF01EW5ofNSzx7cewzTLWmh"
    "Sbe1uSKZKPyYZqr8Nf68N5seRRwZxVu7GmJ1vCe4yZYMbn44giWrg5t5EcrPDmsEV5unI7F1u2n1TvNR9eH9VnVyxMqPu9eStFxl"
    "SgUDneHfJiOdMF9kpJNvMtLJMHxpoh023Cl6I52s6GZo/QsCMnZxNrZ336pw0KMxsuXNjOzq+QX8BJaVZHjrLm1hm7GavXTNsiYA"
    "GHa0xHWOY9/I0tvZlJCSl6xd+vA7C1/bTzu5EOktfcy6ZwkD96C5NAS6WoFLgwt0xoNJJSJEuXNVfTjE8/7iMYS7jh9tVS+eVh+O"
    "MMtoDGr3UBdoFQ0LfwbaNiM3fwM+JIrKC9tBEycfp2AzJ99MqjnzuPwFmlnBXD1+bT/tpBXdUN3HabU7fPl1onI3p8gLOqXIU8y5"
    "DU0p2qB09fCkmryFFc+LbEQ/49ANyrwqiKuYZXmishVl6l2Ay8dP88lufFxLqNbSgvR03puwD16hEXn1upNouyo1Gp4r6mvNmJT2"
    "/IhrUABFxbFw7ITfgjOx8UR9ptsTJfoT9ZmfqE8L70K1M8NjN4O7Fxjb2F5gmYxIJIWaM2ZUuY8RK81EJ40kM0lErMyoqV0Ac7DJ"
    "XcBroAYMoT9kaT/1dwFGnptd8LU62559vCrPrwZvApFIxVy4JGFUpYxhiDWM2Dg5AohM9wHEP8UHcHwCbx4+gNBHg5vUylszDWm1"
    "kJUV1zaa7NhQYPFhtD0xSkjVETFK7uPjVhKjtHMqc5kxiatv3tnwHoCv7acdsKwbwrjYhhRrVCaRu3BZxCETaFlNII8JrGt1Oi0P"
    "dvHs171qMDup7iAJVF6onMoxQg+JJUu99exA5ArNVxPYcB/ei+1q96fqwdNy+n5AbMN3Wgp72gLBDcjUciJI5MUm4F/s1v/+SW3B"
    "7E3Kk4t6dnONdmukU2H7tsZ8LRqNzTQ+qcYAhI1w/5hqw6tFwsJYF65VSgOjwDvbmTrhtr0JgGw/nW/ZDgHKpRDBx2nh754eaV5+"
    "2MMLqNi63bR4p/3N8V65v109n1bj3er4ovyy70cNJGALglEDugVqpXG2qMjBpgAzuBoQS+JMpvBzmprgU/COw6/tp34eJvNO4JNq"
    "/DRm36TtC5cnEqKdgROYM+NAqJ4TaK+46dfqxWPYAgDcgdQZpONgI+Dld2iiB0+rl28wpSvESHbcfpYV5AllPdF1WZjJ68uw8jxL"
    "hAvuX/7iYyzzpz0CG5wlhfZASjpsWFg4DYLgbgBSMr3D+ZYSfbilMUqmKbQjAugkAmlqh0usGw5+4+gkyHdAhLfPrrToJN7JhBVu"
    "pO7T45jzliccM1+NX4HBG8KvEEv6FfMH8BOuFvbOYCeGp8PIhkwelOMO8vyJcDS3HxmOE0G5Gm54Z/2uBq4zr5Oj+L+y3+HsJEc5"
    "Aj2bLXFenm7HBPF0kntRHIYZHyKMA399RBgH4mumsm1++M4i1nKWdnPZnCGKKBjbwc4RJiZ2dY1mUeb6cJ/Oy1encVHxAh+02ixS"
    "OnjcZMYY44qqHXQNTPzb0cIpd96ieVN3Cr2s+l+wsOVaHiwrMInel1zrb38+uTTFTZJra0yREXIcOWHi4DxsJrNmZlZmAFUzDhxt"
    "4uDX9tPO+XJh4J/Oyx92I8+XGFx5QT231Pl6sA9HDDPRk/n4vXHffZNGcIZbK3y6xF+tCEOw7rSe2wzcQCtG6zZgqhKdSzrHn1P+"
    "MZ3jfzadH3yLM2t+whg0sd9tX4LzCD0jKo2kTBO3CukG5qB2rfBP5wY1NnR/Zp73JnFaA9dUIRANtfiaqp5f2lmEiuv6DYdOYbRZ"
    "iBGa8m6OXqiQYbiwUfPT6dEWY9mIkfmBzKua7frWmirly1jC5dJxCupOstMoOHrDaQo52TTFzgfuJPjafNpJ2LrZ/k/n1cOjuKdJ"
    "OnUKOpEYbw4kbLMCOhuTsAUDbvoVj9C9u/PxxJS1Py5fGYQHT0cYXQy+Gtgp4jaSgkI6S5VwtwTlBsco78zq5G7ElKbCNa51GGQm"
    "c8HA0e597c01D0DhkyO8ll6+KX98Vx+jyV08Rmj1BacRO0IYt9itNZpMnbcSIo3Hw2PeMsnT9q2E3nJ6Ell/TO7aJB5fVc8v6knE"
    "fhlwZtoNeAqBgdvwbTSkWSifIjB6OMKi/Yf2THVBZJKZFEnu3lkruZfslAoBmFy0kkyRathWyttPfTQBYuSb9X8/PwQHMOJRTyEw"
    "3AJJVDgixFQBhh2JzJ1dQoB7a374FCLCGA7ar3YvMRD0fApVqmgv2+6BseztAJYrutYJe0hcUtjfNZpM6Hw1s3tRPbsfg9XIXXup"
    "yHLaXlJUtp60lwBGcYKenulXA4H3vXXBqAQQ9I8KgNveBg8DYwlzT9ENbn8E7daz+/ludbEfMbvCSdYUCdfBjYswDDg6EfC5Fq0y"
    "+/mqfGRSttg7g4TRI7ytPCwMJgMjsTDd1ttcPvXS2EETdhVOwWbCKGZSpYStizE1nfVE1gAJYz71D5dyD9fnu8bojzlf7s2lc0Xe"
    "XEJQG6D/5to9Amoas0DWJdE6HXX8Pbi8yFAoo+8unZMGlkyEWEm+jiMErJ7jy73Z9EkMM4hTUQ246ZxOiNqM9eCE6PGknlrsFBoG"
    "wlTvBB9x7AoxkTzL27obRrOEuFfaTabUzd0B+dFpzJR6m7YI4/cM20oxqFi1ZVu5d1wdXzWMTGj9c2Xyn46tVTAkCAlPMnNLVboM"
    "LBTQbnWweY7F4+3Ult+9iUBvCHjO2t1KeFgGaUCSXfUjLObjo/KHKxObe1K9xMAf12FYdURb+BMasbwYIYeahwVBiqvAgtkhU6eC"
    "Iq5a+XNQT6mQBU+hDFxggRmjwRv20w6JkQvjutyDzfzj/WrnvHoIYbaYM4blZXVBeKoZecYgzakjzpjpVg2NfXDaEq/kCOjzzxlR"
    "noIddDwSKiBou75mI4xjJsCZ9pdvliSYyxIWTmxKDQUXYsh1Bqjg4zf1VFv0+fcX8A0QhYWymQt/3wwK7CqZXVslhf5zcJWkIKMj"
    "OFQaH5W6wcnV8MKZGZRaZ6lJYkq0uIJkG/i1/dQ3uLFgyFnrqCS2Fi56J0W+gHBNH7gzxTI1fdXkDVSe2UWzSezhtnWoofmzfXA6"
    "oZgXs0uu2a7Rnw3Hl2GwhKHd1Nf1QA8k0EGsupLXzi1W7ykIZfKMDSj0U34oM/UQJCaie3ZcfT/cMtRJLv163rDtbUOvRF57UbDZ"
    "dMr4XGmo6mRoCxCuVsUIn3wvBk4BY+34qPi1dy90Fl0uHxgdEr+GfccUvK5tbpGIX/uwIe45W5fT6iwyZ628OJHgdE4NHtWonPV4"
    "r3x3gY/qFN0xpNcJ5Kx1yMpa1GY5fVe9+oq3f065F3Z0hCEleE8Bt3YDUCtZbzuFUhUca6PTVOZ0ATd8bT/twKHdyPqX7fL+8HJ9"
    "YcOA9WJnCNukTGlNOX795i8Eb/9lH8OC2Dv0AG3NiWv9CgwMRtrW1xo/PeIGxUTUGNkhEzsAJ2CDprQGcLMwL7wBqPTjoOEi8xaf"
    "uYv/9R4c9giuBgdEoROBuXT6pLPlTvp3X6rvL012shhpdEn9s94U40a02g4VIahbBvkaPPA4SOrAC91z4Fd+wduZFByKBbF835oW"
    "5IG3n3ZAE65t939fQm3BzqQ8v5h9HF7Hr5PCKYSxtVwUdILEwBPLdHxhoRPlDuKzZdFJSkNRHbVeRQ9ugtOJG54IF8l9k1i1M73l"
    "ziQm6gNRQK9qE4rgKHNpQZKta+xYtJfpEfpIaZADp//XzR/Av4CdLDolREILqqLfDo2wlHCgm7g366lDywdMXhhDD/CoNpI6WE+e"
    "Osk0OD2nR5C9ehWTT5UIOqs9YqTOIhzivrrsgENbXnwLNBKmSBOCY3CE8k4mtVA6kEkd2CKi9dMR8oCEPWIXSNZxiGGkG1lqO3fg"
    "30pDZGSMpKLXFZbcz5um2l/q6mQMQIrnF+WPb8uXkwgUQuZTGxV0UQsf5Aq1RS2z6WOLBDQdxPyD5c/uO950C9X0a3n22PIb+VtH"
    "5Ayt9sDC2zFS7lDBaJyIh+BfjTtkJlJmTEF1RMNvFGZMh6/tp50CHMdCKncOY/BbecJgxC1mgog0A6Kcx0VCWgy++QlNpdNpTb4A"
    "QK4u66yx9SIR/rPpGED+CGO8qj4fGQ6kEbUB7IiDG8COf3OIfghqQFABIx9Id4TdDiP67acdS8k7+kfV2XZMEX6WpA4Hg04kD+dw"
    "JAey/iHw0vIhJPUxbLV7DBRU+KBDv2ydoKYQXLYvhF0k3WSxuzB5niwPZ/EJmx0yA0OOy2LKYpyIIvDWZpvh7tUqN9jF62S7q2Hz"
    "xdhMcLlwxMQ5wvH/dXh7wXZaXBnT4e1lLvTIzK6IIm52gWdZGE28hsUfYSRs6YUG1xIbazQSBlM2UycVRk+qzIgkd9loV0QS2qw/"
    "s4yQYvH6sw4jZKqdhB3MyTNQRygPHsbIJMhEZe0lkCUSS2PCFrOUVDFM2L4F4Ga7/M/Q6WSZod4I2rcqI+GBtmfrzX8zl8YZ+nx8"
    "FcO6KJPC8TPzJEUBigCYk8uUQS3c4vLOnfPqA6Iu59+/AQDUweGWLq7lOiFitQC/2bbUjAsOUJZu3W6avnO7enX1i+a/lz8AvHP+"
    "3eV8cjm///QXoaKz3t8A2ZlqbzK/B2IM1JrjlBHHMqV4WguWsJXn+GBZVAbRXs5M1C/rA4RyWX/ayfH5pxLqi6LSfKY6tWHuDGuG"
    "GepOuDSWSfM13aqZ6bIud43SbImsHxCrjN/PLi+ZzOqCqRFLt267fyEtq+BWpna5PGEaNvM2M5VqqaTUKcvwbU57wBTwtf20U5/i"
    "+Tdv4UAMDwIKj5lQEOUp4IeDVFkMB+XOW/BjzY0M5W0tA/wwDsrZdAyVS/AOAzf/uWUl7BJQUoStdmhUuGpTql84dcywSqp8AZFc"
    "S0Cp/DVWLmCm3HkfR3WiMLRbP7sqzPdvVBMUpU4UVk0AKGW9yNApfHaxkqtX4C3w+yAeeYAWNZpVbpwry0moII6MeMRxnJsJU5mZ"
    "kxr+D60rlKOjlPwgTmE+9c+xdMCG5f3L8uLbGIZR9KgalhCaXxTiaMvwi0KC/d5dZArRJqAUvFmxH8ShW2t1jHDpasr7V9XZnw0j"
    "1CKuGpFwTxbPYAtDKVCRMpu3GJoC3T2a/QzJdwMCnFQTpFpRgnceQS0Uuj3Dcp9uq8bWRf2LdOt2de+u+TuIl8+OlUqG5ZvLfYpU"
    "Q32+SrnJgVmGDyL3KepPO/woDoYUhCIfDC8qUEmKnF+NU5r2l5TJpUrKqgenYJGZsvFMU+6I7QzlMXoCA52oq3KplG9A9oTUP/VU"
    "PnwNvkhUzaMbKMstCUqApUjkKQNU2yCWIpC2nAA633QI7x6l+AiNgEU0Rd1fBsI8rrduN211OIgKhRxE4dWRNIWiR4DiMdJwnrgh"
    "oFU4DjiBOmVQ6mN8Bs3p5Bd+bT/tUP675sRDLGmOQgghFMZJHcteclIZT05qOoXmRCrYKOQhLGgA/x+ueoFqz17yGSuig0YjmfaC"
    "YRJBO8mzRLssmyvDCoBUMwAADEwAqi+gKLAXKyB9HGiq3Mjd/vbsYjj2z+Z0WpY8IpmtC0YLnfqW38OTGiLwEl60mnjIJj3SrJv0"
    "UHneUoRGNFoe3K+eTy0UTMeTTtnBbsZ8NNMnAcNr3ECDAgtz1MPX9tMOpt6psAOytJMYFyFjLo6eUwuNnGZUnoPIPD95XGNBsFMY"
    "mO2oPalChajnFrdofgLQp2Rs6zYGcZFlfvd1MIbkfkD5FDgVhE/Bs54EaOYChFcGBZdwBeQFRmBglD2OBXrp+GlHFsyB/cMiRNMn"
    "G875hkoOqzEJaitGVd8vYqSCqDuWepsemnIbU38XS27VNAXVNjuT8tVb3CJAELl1uzrersa75V8uQbv1IW4Tj/EqzETY+a0tSLrf"
    "u1tCEOodlUj12Oq7lHZUvm49PFhwwQD/DcQeWK5JjGmrEtalRstdUxtXSEVKyzkSyTD+YjN7iBVshLqjK9lElh7PtOhvGxlPlIZT"
    "Qm6QjUpoM8N+Zph4kTuvnbQwUZro+GKI6/Q2SFT0oqX3KBJGCaqvKH5BYcNtP6joxepFzf0w7vITCKD2FqZSJDKsnm2CkSAPFyO6"
    "hjwt/qGSXBsnLGhCKy3lYhIO28v1ZtkM9Y8zqR+Gq/boxOGc0YlCCyng5LAcsNlEWMjDfny8KE++oHP68GR+/AT2ImdY1+U4J0Lm"
    "oUhQuCF3MBrvJgGiPXXzQRuofPK4nCJ6/uQxGTqnjgHMQ41Zpiuw8yLR7uO3Gn+I5anSSiqltXnBBJ3Jxq/tp51Iuhtl3d+e//Oj"
    "GNJwBzKdJZxIl9T6w2op/eHqYs/hDOcZus9BS9Ur++1aqqvPcPgEc2686BFkXSOm0cDoaluAE2UHOTdsKYuJiOYPPlWTuziNz8eA"
    "pYJp3D2ybqXRDOzJPPU0gj8BcO4VFm0XKUSf/NitAkANtUTaY9bqvPGcpN3KWFIUq08643wKgfW5GHMF+HRYgsN8bT7toONd4MIj"
    "0NOMYXJB6o6GyUXSmkZgBcawIwe4VkzvTBApG2VLaBh122p5W0yFmk8MQwLncdTEK8hlT8kZy1ZeV+rwuSCVBtN8AJ9L3mEmx5Sc"
    "swlePI4JNiC7SMOUDPhEKvJOBRuIyDvQkH/GkzubbpdTs/a6p6CUbsCMCoEr3fMuaAKyLCOXGkZKFpKzpHBjzKtjHeOpzBljGT7a"
    "Wc+DCV/bTztJFjeA+GgcEyiWRg22ybHQKRYGweyYhcaO1JgS3I0DKeUmb+AXT494WisW2D86OLxjfoIqqqe7fmBACcMFc93Dc36F"
    "xB3RlIEbCzLCJCuNK6xMOLlHkaDZDKpL14vYFGczHMcwSLgqmFkiw6WmJuhFcmETIcGDQ0uIYzrVWE9p1lX1LhRFuWU7SBhUUrkn"
    "u8s3tLy16/uA7lkDHpI4RmyvOgXL9sOM2HCtLsGIbdWnMLwOfcOkJtDYBAo4h7YEttUL4GwolIVxcb51+7+HZPnzafVdJz4nsgKt"
    "6mvHsP0FmjW7p67FpQBYO2u2ifUXojBwIL6YNVsUHciX8PdJdTacSzVLNMSpW3IPMDHWF2xBypzhyhROE57UmQD0aNPqnernt4Ay"
    "ffnmb+aT8W3GfnFNhhb7ff227v4eytncu1sdX5Y/3jcko9UDQlzGzhyxh3AeNxOwY1mqhSOiZnDdJDVIFhRR4/4e2it/fBfjwaUu"
    "32WOFzuRGKQJuII5PNjOF1DljWyixxfWF85zQTPGYW+C62L7tj5HmHuorYP98i0gHWOAE55AhCRUwHUO8YQhMzkfv50ffIshbPwJ"
    "68p2j4EmBTmiRbceRmWA9u9PvgUbfXVlLKktDVe2HfL0aKv6MpkfXVS7V/PdaTACFf7UyEJT6G07UURQCqdtM8lauxC8yEzYT/dd"
    "4PC1/bRjR7mY3YNDsGQiSM8weVJvGWSeJXgFB+VqHV7Bhyc28GH6ZHTj8y6Hc8FQ0ro3Jx9o0/4EqTiuafZHN/HRWebcK9royt65"
    "edvVpF/NFGKYEYjkodt9a13Un/qhMq/S/OCwPIvCdTpGnaZsZp5njJaT6hILQ0Xo4VM8zIdPrVah6ReSdOSkEIMq+AAuO50YVcf+"
    "EDGTLHGhojeR63Jj/AdY3xuls104Vd1QLal7FbvEDavTsIOY3U6FqU/zi8puVLFmh38XkS+5GAmymBQHTTmlMAUbr0406PgcThB2"
    "u6c6sYOOB0Kk7g74t+X/b2f5MUPSLn9MAYxKFApqNhdsLmixDipzukisA/yYH7CSxfQOafE58YQOawi8b2zLIBKyDsRRaUmpftkR"
    "U1c3XZ2qEu5qa64kGm2nVYILY2EpGYlxxK/tpx0bXC+9AfIk9bThNbEBDMNAFDDFYXh48BjICb0NwEbm2vKOPzoTkce/bbzaPQHv"
    "9ugE1AJQJ4NEnNthEzcATsLmbgCEHClDfyYM52nWT/PQLYQs3AfgyePZx9PqxdO4SHXmKF5lSZEScqm5xJzkYoUZrEO88CDNX6yK"
    "mBJqhGhNt65WBrlP+1vceVvtHtkQicqU0e8N5yVIDS071s0Eoe3sCeDyAFNaZZiCIjKQuaw/7RjUrvP05HH1LIrc0qEzhRrBYq2U"
    "dyyTYkSsiu0LcRMLTvo60pdEu4HpjKi1eib//FNMBXqecOaiQlVY2lJByRSDCFTExfngUXWxV6fjfryPoC0sAXAhdzkeoWGXZdOg"
    "+ckMFV9OOdIcUkB3y5c1YiZ4XeJgqbze6qUyyewtAzZgCZE1E/VDNE7LltrJ3jafdsLHLpjzzz+VP8ZI3WQOGLhIUkaFjxXayxFk"
    "Hk5x9xQAJfikncBPNexMZZ1QBFCSkmA+7CgVrYVury8qKFzhiPL7q/L/2S9fDedmzBLuaUcgDKBHT0guqycEGpfjqyZbhrD8rk06"
    "vJnTI85zm8VhvKtuAPpEJAc3B8mp5p8e3cxsLZhBotrKzq/kmQRdoZqiNVygj1/bTzt8zG4A6Gxv9iGSj1l7LgoPcyc11VZhcane"
    "YimIzE3eolc6QmxDXKlVPSQst+HZ6BrXJxJqBl9AzRw9F/K84qAX6r6ApKSbal9lFRbwLqcFdAG4vsBy6aVoTgsfLwP4GXcLVNO3"
    "MfjePAFm0xY8z/rB8/kNwfN1//DOlYUxK320O+9Fuy+NtW/+aiQCoBI+ZjqIxxgnZ9PAeYZaKIazvaeywn7aqcV0fZczEB6Lux0M"
    "nVbzVPSUYkqK3GGRAHL5I3CqoD0ruBoZKjhfBTlUvrVQV/nDkRmtofbgcoQB7OBFgaOkHgVJFkgDpmMthZkQtSo4x6gV52CEYd/p"
    "K4F3olZQqOmuu0nQzT5sV8fbkcSkPqIuSxBmRuCS8Z2NwCWXZ/uApzk43JJF52JXhUYzJ+xwZrTDmXlatJ0gk3YrcG/Cr6UC0xs1"
    "pa7cTRaWQLnhlDKJyDV/SheWuzYNzS6elOcX5ee7wgYBmdi6bf+QdGXsyOil2VQiFSkgFPCgpAVC0YxWs+glTUkLn9uXSReIiviQ"
    "avJ6/uCk+teT+fhJyxIWk3Frz1KRIM5hbegYUYiRCV8TCTfqEJmOrc+BSb3IAPY3agpd0fP1VnPhFN4YX8SzdMQzF2LUDLr8uF3d"
    "uzubbm/9zTXWCBJoRPw2vdBUzbGZvr8OrshYumgzDMcVMUztOzvn+yfVyXBBEhAfdLWnJDrCBIG+IAwaSi3oZ7xDkW0KcsSIX5TG"
    "zPQo8DE+EjRDCtQeJVZKepqKHdcEBdNW8K7lntlwDAiaCAVw5smoI389rQAeJaPeSHWbThkSa4n5h4HI7E4LxigMqocHnzUcG5XQ"
    "cI2KteOsLXjaAoMs4VsvzprzDmsHUtw3q/ylnA4H52XIOtPW2IC6bE+NTbi6anBdzHw8Mf0z/H5s1KF2gLoYkiysR3gNu72+9w2q"
    "HNoJRu3JGNvQ417VSJJCHCNKCpGqa9h5a+tPqpNtC7HmoGYVKmFf1IQZF9qGHcsdCrtI87CHJRWHurlzJMzhEHiCmBpwjkSXtsBf"
    "5vn+cIawPFHoRzVRl/AyN1GXGBXEUOgDe2dUEFP0tJaPomBTEhc+HyFg3o/esHiuApwLKuSyqV3hhVysIgQ64Ko/5NJRhBB4mppd"
    "Ab529fxywaWaOxF5mWgIRwyPlEPl+fu6ht7ERECGoejaHhyqdG7RsX5J6TAN/6ubumJDxBu8l3GswcWGkRPZYq7FTdjo+kLwMhVI"
    "ngorDkRtVJDNfG0+7UQD3IzXj1AEMLvci7nxHfaSjAKJ2WiAkSIbXPg9eQ1xMIgGpByLlYY5/+b38JDzfIQ5TNtQp3Kt0Lhnwnd9"
    "jyLxxmBgOG2ZxlBAZn0OUxrTGwrIeAdnizews8ZnuzHs9CIpnOselOHCLEeoac3J4v5+scLq81NLUAYpF6N4iqTYg7k/Q02Zn8CN"
    "Rd/LExRPibW3wyUiqkKQMDCdMBAEXeUhr+cUpMIZHm/dA7RuVMUhxOfn2VzXCEPWMThABwaqExXG/yjYmLQaXhC+B8yUNl/2ETgq"
    "bf2cvYsBBioJmKbtFLFGyuYc+lJiRZpIUEi/ud8JGoTO5H6Np4x03HrI59FSkzSV4MIk5kus/BRKjFgWn8esRwV3qs5GGAXw85gk"
    "kkdrBxlPct7Y5C2lX+jZWKvOXjKTnNJwv7ZQs7DAbFdQGA9ivfbnF9V355HVYgiqbF7PMJoBL3ZSRIuKpR/sVztTwFxBVdIO+kuM"
    "Z6zDr6yKDBXBhz2tbaPmJ1RKzDNSPd6DS3Zf0U2VBdrpY4LnHEPp0ON+FnL7aScd6eZNzi+q6de4c869V1RRkrIsx7XOY1iTXtwH"
    "XREQf73YLh9+wfBdUXTDd0KleTAkGxpM+WEPCK6e78PeOb+oHr4ezL3Udgc5uKfl9Gn58LXBY0Ox6rC/jsjSwDwOYdHCGaaDjh7F"
    "1spYmACorJS2ZJTmpe5nYZKd+jfhQfbPL2fT4ay0WcKcbKdOWPipbsBR4ZT3AFST6VdjohGcH7Y7VGp69dha77R6fs35ZTV+yuNo"
    "GZHUuAVxhkVMLS0kUX66KDBRvfpaHRoSHexhzcwo5CikYDq8udnFxEJFRFfikstM8fgoBy/0gENn52lTMLR69pEUw9h8hruD9zM0"
    "5n5MmeGEeHslJqacekFlQiPBBpXFDYPK1cWelTjmykgc+wHl4fJ9ZON4T5OVjjhaKjK9MZUEh6tJ2GRCsZirCbCnfqjbe9GvqvHw"
    "wIdKUBahiXSrcDIOg7V5HFUTEHaYwBQwMhv0IZOGVtLj3emh5e9J+Kj1pg+wusqZ04gsXJ4wnMY2fUBADIwCajjQMFz11fTOnKVu"
    "uRGGCyLLjbotG4OHOEl2rGQ2wQF1EuslRZKtOtxgZxZrCU0PjK7wAk3MzPeKhAfg+stleRyjHc4QUFTbMMY5Jor4dWQRP4CxkUDD"
    "dMqIh4e84UW/b3/C4qJshJoJHguAJj0i5iG8OjaR9nLonsXKEwYzsVKL1c6hKc2H1VYZ+MA4nL4q/s5qe8xXf7kCno8oRL92ILwY"
    "YCML+SWjootkIX/LHlqeva6OMY2UZ0ZtLfjAacUG4e3pQGCWJoVbE7N8aIkr9zKdPi1f7gPXegQAUluYSDO7BKUghkMoYAMRHAIa"
    "DBtgevnGWiVIapSNUHEq6Lz5SJDunGY9tJ+eN3eDcF3honCmkxhjD8jH3bynJgAEOUTBRYyt1xrxYAdAfP7Rlukcvv55QaWkTJeo"
    "9KNe61vPsRi1mcqjuLJS6TAgZgkSvhKcd5jliuK82wX+Djjz2CljQFE3sixIWXfbrdW7M/4hdz3+6dlsGsPEDYXnzt251pJNPNz5"
    "SOHr5oV/8U8GgtybhmGU473ZBSjvYCAx0yOsVw9eHG6F/bWrmGbbFusIHOPh1hIeT0ABwv9ix3vEh4RfmG8Wo110oP/5IUYXgMOm"
    "dWobWG+kJ0zOMKR+zUQklO5SHUHNWshyGhI9Mj99xkp8lgEtO4YefhEblbCzsEztA181fXA91SbHDrEI1sMp66Tj/doH4V8G7+C5"
    "j+NNyxKOvFdNnJnIKTCeCQZxSsIznV1O0fod70HEH2L/D98C7S9wVO5vA44KQKSHWyyX+ciwVl1HYS1sZH74bnaJhjSTINPoNu1n"
    "65nSKAQZ3gcwZCoMvLE8A0ypBpBjwdBvgiHREWD42n7qvwee3MX0XfXqCkh0hz8JLpRVJ4x4WOu6p7ADtbBA6Xhi656QZVhQbBq2"
    "N9QRXb0QrY9tKTozGZWxAY56NzmH0H06ORejadDm0UyfWlZek7SJzcaBevzxFViLp0dbeSoN8ayf5SNS6WaUVI7OpYbtaL97Gj2r"
    "8UdxJjkm3wznEeKaWhLdcJ6uE81NPVru6bu4JJ1yorlgWfD1kmAIK3gbNnnIWKt1kymbxy1jWt4wFRhGbyZyWu68h/v8L8NLhiAB"
    "3E6nSmQfG2ofdiTAhjo/RnFEx0YBFTPihbAdCc4ldEv3aNe5JsYNrHxPWHT60+wyZhpz6e7KFGHsxDTCEYpSm3wMZZUwjUcns+nd"
    "5iZCElxPbpLm9s9lTxo2FUUPtz9fDQYndzE4059iVODzpL3lIX+lN5fnM1799dxc0M+nbmnb5zWmUtHuciZ3+rQ6Gj6/CoQ83DsV"
    "gmrBiC5KcBFZaW/3Tu7OLgzD17MmuvfkcfUc6QM1wlFcFt8Uee1739RAi9WXE4NwYaiHwDUVM7QDpC5qN4a4ZgJenECpCymQLTA1"
    "CshBQDB+bT/tCIN5McefDCt4zAuKDkez2j1l9/CCiuVe0Cm6FghpyrMRFnGEn9CsR9SdUiwFxJl2gd43eEM95OUHyBrEwDkc8T+d"
    "cECXUk5+Fu3kw0X1AqNk1fFF9RLhHFwx9PMHe/VOIw/2bTsQyuFqBNTXSJs1gSrH5/+lOnvSKREVjIfxSP5vkegSUpLQztUmTp2d"
    "fYXOvKn6RL4eXI0ev79T1qa8eNCHfZDji7JbC+3qjgsKXMYhgzJEd9yIhKGXsQ/YXDx1k9cYpzrfEiwbIWwweOiwL6TdStpaMpF8"
    "6SIJn/XSjUsjtDjitXLYDm14lQY76xuCnWGjoxetu9JpWiDjZfC50Vkv6o0Ke2Us0ctTfvjACXe3Xnw7u7yEXXI4jkmmqCTzyjEJ"
    "glmZgZ/HFMHd49Yzw7+YEoDy/BKoHrBPONGmj3UMO+hkD23K1Mmb7C8T0qQSnWh4zqiqEjvi4MLZ8W/EULAzirlcACnCKGhDAb82"
    "n3b8bNcsvPi22pvEsSQK7hneYd+wNrz5DQ1v4L4w9LIQyvYT9lxmeGMsDbdrRm8griOK/MWOmTLjV6/HsRg2Jw2tMEJVeT9sTnbp"
    "+z16+YtvIfz049fyYHghqUwypO1v9gBBaYCKi5RsKCFVOR+jyqWpAiovkME/t5joYWKXbQtmcBzdAL/0QYkUGXaDbnGm+oCSroG5"
    "bqBkPYMyKwpuyh1MORlRNMx5/WmHwcK1Zi++nR/ECDakqGnZ0lcImr4iI0wUgr6ievW1/GgKu7FTSCOeYUzaY69AptS+az/UpPmz"
    "Ol3FNNu6bf4IzN3xXvllvzy+Cueurn1GmbI4NdS7wDb2LpipFwJMRJ6mMNgeCS7kGcFPOwhA3ziIsWPzhIPYY3shhNFf5gIDqNpS"
    "leUP4Kdmt2DwHbzgzpOgl6k0b5t2SXRknsOuGe9WX97Ov/+naucC0iivLgEtNR2H9w7xMYgLwX79+Gk+fkeCtV3FzO6948LI1v/K"
    "OKw5MAt9YEIeZs3xMFCftw3X92BwNkJ0GnA2Is1oxo8wZc5wJVzsHT40kgaYYZeIs44dXF8kT+EF2MzlXUjADncxU8wk1nMpsNQk"
    "qKIoGBO9mqXXtA8/34WU8Hz83qg3bKl81AWZZBkWLw0UUzQNVjtXYPTBvZ1rEOKy7ZOlRThEYm1EltGe6+o1amEeFR4gaaismZGB"
    "IPUQhf20owAiOisOkecoDRi3CibDPAStARNT3RBSaak7uCV4MBAV1RQ84RCLkiN9TUyGJN7B8RJXJ45+Q1cnzicqOpjKBiTSRGx9"
    "j/hD2kESeBWLn3dnH4dH7WWSoyhxnboLc9g3KadsqZQThpcxjFvQAg25xdGYf6jzCT0kDGqeA6p3JYEP5TEpfNmdXe7Bfowwg4Fk"
    "so2PqwRFzIh5JVlpCX1I7E+tgfMDwtuzXBl4ethBcaEx3elcb5lI7gYPvuyChR2RswMuJheISwgm135jHxVej9dnugVFAnTyB3rS"
    "Q7lM5H6YFEkBMdoVZBhcmU1gb8FDXn7cXsDpwQE06aRpCEoPYxjFUHrsHs1+Bs5zTBSM9+raMuyZwTywUcgRW6Y5wxbEU92l1NfC"
    "BAwDK2aHTqbrSHERAGSsGE1aTzCUZhumbI4qP2EeffO1+bQTj3VsZJya05iL3qF1zRPVo0VPYjQo4sKdcxDRqNcLKwQyrTDrPZD6"
    "sGmhfPIYlC9QIzPtSpcLjsHI8PtBUsXawW7Et7bTJ4TIUo3mnClbzEnWNvtpJ+TmGPA4p59jbDmnus7eW1Q6UcTTaU1/Kk++WDxO"
    "dYGFNlIbaeLhIOG2ERycibEX4DvvlTsX1YP9aylEgnC//n5r9vFT9frJ/PBp9fKNITEI231kNV7nhl9/MhGD87mpyGKmnnkBiLhT"
    "kcVdDgGYyE/ncagtRL21AGJKRtfyjw0QXr5AdXsAkJ5aydv5g082Hm/BisGzK8i31fYr+LgyljD3Fr9BogtfPmcmf76KUacAvjg3"
    "x5EjpUBYEohBAfsykkAAKZjsgtfMU2bmcljUqmmhzWdpIUYST5tpssvpLFGwJXiAcKTENYvj3ozjxFSqtcKicMPqgyWLyNkdYmoG"
    "vWr8tGPmO14zPEFRpqkrTJwlqocRjybhCAN+4RY7MaGmnfdW/t2AnIOnBzsSXBLolurBPC5fauob+YU/jf/lW5PxjjFOXKJRo/1E"
    "2PnZENuktfNtf8BbutyzOQNIDguLIh2WI2pbQXL0XUBhvwK9py2mVJdaFuSPKCOFThThoDdjo5hpBArclGko9FV9zLLwtfm0E2T0"
    "jdEYQiydFKjg00CesEaQKF4gAcMEeuwYA+l4eEAsdqtQOZmptR0hnh7ulQx2QSxulOgmT4/jIQMI78NR5NPjpNtyiKLQanRkanXR"
    "04Pdsuaa6SCiyDTv5N64kq108VLtY8vGscUkO0I6ww8RmUuzs7CxhwgSriDMgTBMhvxyVPKDqfrTjh6h79wDLCxiBzguPow9790B"
    "EcmP0AoB0fnBIb5ILf3OMg211ohRwPB2ETJLhJfdwz1dW3cqdp+lSb7q2H09pa0VYuvA0igrhBWdxb+IQlY4xz9LcqIKrNadXYys"
    "uKaxW73crWurWc6QlzscHyPPI3SLIn3MeZItT5nsvUcuIw2w2d8DyzbKhm8JSWSiAVG8CRZqjgkQwtamdIqgf4vJT3O4JVfDpqC8"
    "gMQVZNRjoOJeCFKtFykuUtmpt4DK9RDceWGjOFB8h4QcEeF1GB55JeFwe7guXA2jVZatI4kplq0zgRkl2c932ilbN/Sz7XJD2m0Z"
    "XTaRKKABaWMMYdJbJDRGOvulKKWxf9UxSH5tsUKaGH4smTQqx2OUGcJQTpN3IKD04rH9o/EuKCh8d+l7zFoYRv3r8anQ71Lxapwr"
    "KgoCM7cRiwbWAqqbhSzSwnCRF4upqIGH0WdL9nxCAFFEXMXSQbkXhhGJgHOw1OhPxcM5pns167wcodHqMexh9yMZ9ub398uzvfm9"
    "7er5Bcp3ghhd/dfcsZPgfBMGBF37DHSBgCPmeL96eFydPB6J24IGN9jJC24jO5WbMYy5SFXNx4cbCIHIC6n7/NQ2yMi622h+cB5J"
    "7ykc6eA8UUQCrEYfFzdEH2MPjWSNGA2XZ6fbal2hjqqQzLDkKLAD7JipVAhForJW9LF5hHrJG2v0sfBTIWnmWx5xMENjbLSrrzaz"
    "+oziSbA9IteGlAUViV5NCa1yyZzA7D89jimacdgwdSKzYjMaAcC+R+k1QafoskzX5+tm5sVqav+YdCM49+5Gq5UZXaUGvMj6wYsR"
    "BRJB8te6gyZxp7t8o7Vc2fLssvVfUEsak6kETzWpi5B06UQ2xTHLkOLJiBm3BkDwoYJUvK9X56ChQYP11VVjLgPAJEqk0AG9AFIt"
    "p116PkRcrXXpTcfsKsFPWFmL+9cJYHMy/AJdI30dBNX1UABAwd3NTxvHcHsz0S/KCLCbTqQDO4cixX5XNAyHWeg1AlLLoLKE7mAS"
    "wRMNWJaL28SBGj0z490GPVEpyQQDjrbHE3Xz4iv3RCV6ojmeK9HvicpulsFd7t2j8mD3dnV8gbmc819EnCkX1ZwlHPLGVLZOU+or"
    "hA5VQz1q+ocrjzQ8A3WsWurS+1/gpz//VJeYiQ4bmyqygjyaNKjZjncjySU7g1LLjGE9IYCZFklZwaedAIT7pu4elV/2DEdBTOjB"
    "OekFQfdh3FfSUlkQM3gOrGe48M+mNrXIVc4xUhQbf2jbwp8saSI8oRhZ8GINWLISDiGQpx9nYGMBBBSulDme+5SjRGFPAMF+6t/z"
    "mRsV37X8njH0eNyjRwuXoTXMiWJp5sS6a1tKF10+LmBPJAtEOFkjarsbWi3OuScaexPaJ++InZT3tyMZX7JEOpXdQOsbtFR4DtE9"
    "4MgbNMevn2BJx/EueFUHh1s6A/FXkhIQu0C9eOCfBAPjuS9icBNzxNumJ9XRSQyKRCW5Ux1dszgHPCq4VQuK0CHoUc0+TS2zQzV5"
    "U98tdQdNOkdRbqrtFuVTmRt9ke4aWwnumRUuyG33dcwlIJMMSYhq/z9F1WLClKZyOlR27C+X1al59R+cAloHa1HT7oPNJToGfSiT"
    "UJvw04PT8vRIpKL8gO+Apm1ykr4chqwWKwwov4nVVCKbOZU5L7ihHTBlTQTIJG8+7RSZepfU62p8P0ZmwkVG6DCtTq2FgJIqN1CZ"
    "qJ6/s0BHhnQhy4tKuBWlgsts6zYk3B+Nq2fnkDvcm5QnQK7axeyZHM91kp3Q75JaFTSkAqdvQ3FDg5ir60lhDvrFKUL1pCnS2DU7"
    "53J++HTptFWuqbIJqJnQhIbbAotv9um8+pd9dO6wdw1ryTLpq7Yx2Dvwko/L8yvg3AZtqK4bASYkWyYLlWuSa1knYnlAVI8lyZWW"
    "uSxSUx1mUJ68z5KET31DR7jAgAf7UDx1Njx9LQzveLsZkOWOqKGhCEwGFL3MnxyBFQbIGPMTxj2Xqp+51tTBIfhQcJ8whQgOdy9o"
    "jHsH94LHuN7dCy4Z3podCpxZqIjhObxmwkh3qN7iGZ77aHmFlni7DWIITLKk8AyJHK+HMMYKmBJiSGxaaNSrK6CNNKIQ5l+wxpwX"
    "I9lJ/ijZJvSX/QtwBmofk4zR4riJJwFnYTNPgplXgM4pvTAnXaPslO4Q2SDXqbMDTo8jEd8oVFXHkFg4l4hSFqgGECdlgYADsy6n"
    "xy3jNgn6dqEjnWgP9my1C+ODgVyf58Gj6mI42WGeOMBfEMAijDIOjFVRlRKmI7jPT6egLI6pfZWGojGLWoDhTF6XP+yaskMg9ajb"
    "vGO+2ip/OK++A7qX/2Greng0+/myfLhXfZh0rDKZ51kwy9/byNbflAeHpI1G+bt2NjeUNGGpKgDOKJBCJuVWBZVImrD6005w14UZ"
    "PXgMJOnDTyMqSbfCMj3lF8P0w0IBXexTY5lxzAgEjyPKeRPH0S0AXlMBU8q8I3kaF4NIUS2qTkCm4LgHwjiayZRBbiw0lZC/3Zk6"
    "YZzdIwzjjJ/i9ALVhw7Vg/b+HtT0vXiMVRYaqpVsW3cgofbd6/m9bTBsXjzeKh89NTk2hOAcX1XfvfbPoSw4qtde944Wt7TFUkYe"
    "Rzt3RBITZ3IT5xHXRucQb9dgBiMOnS4ohK/tpx1CTTfW8uAUAXBRDNBYfdBKUhAPJBAY5z3BrABfc7lz2BDQYr/qM6nyERVihf70"
    "ODPMK/Pu5MMyt4LgBkFWr7AQAkUxhOWpU2EGip49MpmcCGEvijvADff9kyaMZeo6GL6ZXnABo1jB9wg7ST1ILh3HOoQ/PJMewnDV"
    "g6dGQC8q3e5Oc4oB2fUFCRnLVCcrXEcJw9E9QzRs/6EA4bbf65UwM2xP3nwP4KDIkgxxQvUEF6KnOpYCAS/0bcz8HhziraCNZnKs"
    "fzQF88OIFIHJVzfZjbQppCoLuks4UmKBcNwbc5eMdZamEjldJRtQlyK7DPGh1R76FLgS9UXCiiBSjOuaEGOITQF/+3OIjKKF0Cx4"
    "xsQQyyLw29XrJ9UYuCa0jbEXklx2mUNciXhncLCEEcCKfEgEXrrlMytRKoO5VTqVrCjSAt3lQvbYBKAHbD7tSG74lmV1tj2fXALN"
    "7oOT6l9P5uMnA1CYXoHaxhiAzTO2PAAXGzLqzipIJBylYmen4b8mUmCOFSKGgWIBLJd3K0RyFtgWMcjcvwopNLuuxHIzSujuJone"
    "Ev+/2RHGOW53RBxbmkQoXgsspjwHo84jI7hIgEzBePPQI8tFUvQQfWFXCJ9BejJRnSsciy9vbmVxr/jqwWnMuZIe4l0nivWTuqRL"
    "kbqYTtUuGMlL4Ze+dQuaWJ8G+koqQoUraFT90wnkfr48ikj8GB7ZRqKeSCBDwoG0YYZka8aT+XOMkRRFHrJkhjCm1aMzlBRsxIAG"
    "1bbbrVXT2NVgwscjpu2q1nsqrJ3kn6cMtjLKNKUMD1oG5itTJrDRT5mW+SEN4eFH9yazy+EaIVmiZFsSrBMZDvhbfqb4kmBks8Xz"
    "9LDGjcqg4xLRxulRXhuzvGAjRIt6eDRKINsOlrr3NlU1VE+m5JlkJrJcwLIXNDWW/dS/Q73I8t6kPI9SM3QeoyxJRVjaSkOVCyUV"
    "54exXr6xeR5QyLXhFuyUkSznI9nF+ZpcVS+AmGy0OtkF8V0wSairGUdIhKtxvJtY63oGZa640gZT1kNED1/bTzvkGd5aH80uH0ZV"
    "/bvEx3lY/HVlzF10GbntCZVqhX6tL5DGvZfy4VEMlw9QEbTxM5UUStJUt6QmFUF1e7BbXSDVLaTj3kxM/MzYbp5mpaJ3Oh0Cxr72"
    "FKy4BsoNCu6YN7cn5aPhYRSZ5E75apZkms5y0QhbIsuFXakjZoylwXrV3l8WhqJnxLduN635xoYqNNaXBZcGx0ZcQjjSzVxCTKTg"
    "0miptRXJ0QsLFuDTTmjUvYQeRoGAZaIcKXeVFGEOJ3OCskG5zFY+dzypjieIK/zujSXhRt4RTPX4Z4jkj1ZeXVf3DGWCNuRTl8Hk"
    "JvQjbmLq4QmQxEbggAGs5OalUKyYYBsjFb6JEq0Xj8EGQwPMdguix3KEALuBZV6dNhz6KyT988rHEBAbWCUzRirVlZNsx3L1pns9"
    "kQDGM5FniCuS7zqWfplPO/FnF67z8ASSVrvvq7Pt6utTCDcN9+P84EKYih09CK4K6n1a7ILtAsk9QHhMnAjxe6owG8Fzv0KI8Ki/"
    "wEwGSNZybo19qjoaB+/kj3oKhDaoU1VPtsxVquDdqpGdNB+2/bQTKfGf1pjsKkA23EshBTH14KVratkHmC3IbY8H+rQp5np4Uh2d"
    "tgCSruFSIMIzeOlyj7qpK7bdd+mupqw9xY3rTO7ZdvnjfeAnewg1+VE0w65ScE6Qe+ocMlaDVM0Pm4k23bI3Z0OpRcf2hCuM2QW0"
    "UgScK6y58lyVh4D+i5lKkSg/IoXVzBQuvYii828rEU+nQPForhnTwa2MGVS6ByEP0QRENH46nY/ftiSAPBMkxYMdNxWXojge1lLZ"
    "CPwIQhYQBQdxPbi1sNs0NRLLu7EJ/9aaHw+X3ZYJQ/nU5i1DRCpxmBTBaEIdpg/va9hbs/Aq75iJBUPamV4vgWwRHirSyMSBUW+T"
    "C3Zdc0gCJ07mSgpLWkMnTfFr+2nHG3BJVh6+jqFl9/lAdCLDEFlTVal4VFVleX4B3gAkzUEe1T/SnIs8ULlENbW/bVtDucRi63bT"
    "OM1MlXJZNP9QgEkcMu2WezbMShLlMJMaSEBkYeQaGOtj44djbT7tFCx7dzu+kRFcRVnCPRV4ZHKggs06XgV+cheOdMuKnHE5Yhj2"
    "8cPDAU7sIa3an4x6pijE1u0e0UPzn8i66B69d4/fYv1xaG10F0zpUSEGSDQIv4od0BTtphjvVuMoYYE84Y6KVJ4oQqe8lmCMgACG"
    "xCybDhoGs2IZ/ESotc934ebPuhLawGGm43PmOCVEnBQnaCO2gJ1ypCzTGDDKaHHtlt1Md5LmGGZq9sdeXNgIVfoa6l/KrobMGNyo"
    "EbHBmvoXO4SbATPFw2KD3i+7ozGq2WrrdnX8CYrwfMt3drEN5RBd6RdVZHl4k/Q2Qib3KXyencCNhRyhNlrLLC2AG4MZ+ui0lyMl"
    "LXw1KEBve3vn3UUMJ6+zebTxi3qYkMKvzULWopNx+fBL45flI+RuCgavsDvEpW/5I/upjgvft7sJIb9ru433YnIhAAB1scQoF0pC"
    "XdVy6aTZB9jgmE7Ks1GugujUZaGvTNYBpXTrdvM3kRYdDpe4iz2t1E3gXZFZX2AG0RJU9JPwiw5UwKNwG+/FcA2ohPlUKOEIs87B"
    "ohgSTALf+OBbi9AvP5sc2IunwCWLOTCRjigpTdsX6jCB1EZoVYo0Kdws/w1OkFdwPd6rjmO8nwzT7c0JIqh/AbMM7sRSB2gKiSr7"
    "RoFxawweppCq0D1LejiVQ2/zeKDkCB/R8Dlyc+7dc7Qxyl4zqXA2tA3Kgu/bPv3BY6Q7QVkmXT/o+4vyYYwTpLQHG8fkfGj5s5Tx"
    "KOZnqwUAdx32yZSHdrkvw+LTgxo0GNB0hKVq9V9BXpw4zuCC21FvaMUze3EKg7Ey+ItWXKyz4ln9qW/Ean/FgfgyorheJ5kjWKgT"
    "xnvSc6RWLmGLPNivxYB+fDsfI5ksS4tshLmloCWSuS5EN48GXVu3Fh2au/VsPjuvpm9japk6nDeEHAjqTlL+YliiE/7gs5Fzfvja"
    "Up6hkJbR+Qxa2xkpYGH7tu659Dgfnk1jBFNBtcQtW8op3xtuzSzO927tLuyTpf0BAEU9qUuYcE1TbVCd8RywGdcGbt2kh50yWZBv"
    "YkFfi26BRDPB5BFLj1O5uSctaxV6YEIGVEJd0wl0K6GeTSH2Gadi7dk0AkKfhLwdVwSgkBSmA14CdLbM+mPQ3tiGQ6XtnBYs8SjE"
    "BjEy4craGQxm+JwLOahGURS6DQBnPVTBK66FqqdWZkUhoMQwTaGQ3VGwuiZ5Zz/tRGtcMPGzafUgpsxUSpevgIWr7JE9hLyaCfYQ"
    "kKdv8iy2iLcA+e1FgK5gEziu6uiZidl1gjFKkwkc5FYmYiukScOkTJhb6bKS5baTKLXOpGEdNsE5IsCSZfWnHdSR9xJPY8L5OtEI"
    "JW0UDnsEDgUF6QrbNLOfr+pQ/sHu/BCJ3JkC6fpsOOaobcQMjONq++kAAayTlJmkC1EMyeXwNHe+ozYB98udVodCgghtwbnhRLCS"
    "Wb0E1LzDicBQG6bZBFcxGJN/c2b/v+7Mco9/8lmU+ghUkrlE/jIMPDOXFZnRI/iiLr4FYQFYlsNLgEjXMVZuuP6GXfpOKy+fVMfb"
    "1b9sV/9k1rcDVCoU8qeE730YJXHvy2IAVSwzXsvqXwCgIdeZyk3+ji1+AVTeKYH3CFEmd0GJCZSNBz8CLut8QREky4wxASG9cDjD"
    "mG1Y6LOF+w+TsJBU+3S+NR+/B9l3JNgZ6Y7YQBYOZ/Q2CCI2k0t0HnINRWS2fSKSYYdIRDIEqccppR8fXsmiwzwqk5ZL0cpjOc2C"
    "g1/bTzsJADdnO7kbKcerPacRMHw9TmNYvGOwp2d6B4cf4Bw38RlNS3D0O4gf8AlpMVbd4+RRpRXrcvLw/s7QDzE234KrPvP5IYXn"
    "5E32yoPD22AIf3g/XGYi80JZ4Bf1gDhkNIijFRE1HUN6SGSCDL/DmrqYbc+I6AtLitVoW3MPwT3Zg7rhCKSbC89VMBYK6JYPeTxb"
    "WFr5EeT5zK6HPmGCO0+7VUVFWDR0WJsYDcY69eCbScbF7Eg3k4Y2cwcANlDsqk2kBVg3nncgLmgZNIsMZVqABhnDNEXx4LfopyJR"
    "aTgGnCFuvF/H2Dxs8C+WG3n6GBD0EOBoish4kXWVeXKGrfY9lqE2zU+IesqLEVLmBHNyOD7imcTRbmTJ7fwJAdEwcIlFDrYxo15I"
    "UX/qv5Coyu4s+ccY5IFTU11YEzmw0EiiaqC1/QtdTe6Wj8YWjQZU53ahPyLMDfSEvGXWEv2svmUOtwg/QXjsw75FPJIZBLKO2g53"
    "MytdTyCIryjENPbU4MDX9tOOWqBnAL8uL76tdoZX0OtEOEquAOwkwiAsR+z/4tQOLOvJF/MsvrZK8qiwixUXsOA6YyNNro3QmROO"
    "6CH6oLyVVWYnPCmzyevyc5T2ilNVASxTtGog1tEvoxpo+oRIkzQbbl+2DQCr5vdPMKKcgqryeXV2N0CoVtAWJo6SypNSUIb1iNla"
    "jUAbPu4DmNQagV3HwtNEnryOOUnAs+gm9rTs5YJUN+SCxM6heSkJLshIfYtu20bKjuaUpNOGMPLNLLqZS6lSxSTaR306VvC1/bQD"
    "h/DMozezCL3CLNFIjNUw8yJmj/AmqWqPhT4g9glWBnIAxpvMiutSVkq3dS7Lt478nO9x9WU+grKB+fho9uk9JLp3f/LETa5lIYNf"
    "UhcHzhxxceA8bs41Nf4mxwCU2UnoF9GuKe8g0xjSwC+3h2RSZC7DBaTWKERAbmT3hiICoLbcuqPPphAlqknr1YiRZY3YG+pskzKF"
    "UiVKrURPimOSpJnLL9V4uC5MlijuC57xXkKgMMxvCJnPyzcQm8U4vpH79Is0Qn7p8GZPj3ia1jBPUp6uBwaD416DcdRLCaSA54cb"
    "ZrqeWG5DCcSZb8qmntNyuD2fxBwig66vD1FGlN3hKWJxuJrq+Ap4STGUD52CVRepCBLYDmzh9Oha4lYISuMDxzbAJoZRk/k7keRA"
    "2bfSaK6dTCEAwLEwiZu3n3bOu2tkH45jjK4skU78HpyHYg0ChzlLRxxdn2GVd9Xzd9XRiRH0kao5yPmIpWBk1+12jGwuKC0RO0ry"
    "rNMSitl6CvEkl5l5LeFJAkgiWYhnP+2suGtxHQKZUXm2Vx3H2F0pxu2b4GOYnlRKDtCiIYQh5UO4jQ2LwzHwfoFB9AmkDYyRLQ1W"
    "w4lTABXNgmx+qFEzXtwQRK2FHRwVfeSaztgIt/JqNTl6M4NSFcqmCkVPJQx8bT/t0Fd5K36J2NsofJZXeskBmhSspGIp02Y79sea"
    "oWbEkHbUSGOuOyLreRZkiAm30ozJCAKPON+63QswtkMiFhkHuJkQM5xoVIMWSmH8icO5xnB9qNKJ1Z92HGfvDr8E2+bLJEZzyCma"
    "B5mcnBYdgu4tIzoEeeEDk4htuQqH/3r14b1Nu+aO2NB1NaFwKdz3T0A1egdgn9X4BF3s+5Pqu9fVl4vq+GKLpbxPUIgsvLdTtXlF"
    "IWPe5UMUhTp3v0fD9fydBekP5n1sr4EsoahzIVTK01h5L4geG5lQwNPUMF9prPvgCdaCZOsxnVuv2IPqTiUSUw2N++Iz0j6g4To4"
    "E/fVRJSfiPuCusbBeV0PZcCOWZ6ZeEXvcxlqAsdlRoQQuE62AKIqVCiZ6753lKxUz1giXQ2v1byjZiKlUloKo5bag3yAr+2nnYC0"
    "v+QxmqlQt9/6xkUiAAZMBKTRVF8mID37+ao9R1YzVXHLXOhHlAfX8QRbxz9DWhoO1jkZnvZUxLvgFxcIvfbwNMwp5zIF6groNMao"
    "yfC0/bTjILtW1PNpHJtWgZTtTQ1PWOPFUBgOKoBsKQyrH0Cm0Sw6dKph01qUnA+1cAbIffvvkMbLtEYRdI8JEVFT11/Z3Z9Aoe+H"
    "6Xz/vLo/2aJVwexsEFcDzs1mrC8z2wAwxtcURot+dNj6KppPOypLLgz6xX0gcPpyBFzaKM+2yLT2UO8a04EEgSk4+TEEptgVtK51"
    "0cWp6yKCzHSyVz2/LM/2yldvMZGfjTgU8dXt0za2JHkxcag93LKuMNZqAI9MpBnYTzlPc7Sc8B1oMb/XOAXsp51H3+WjqPOqMfle"
    "p2YKMuF87fneXKcjkhPTlV7sZngp/eKVZnjdmOOLxzGaGFnioIcLkLLrfU8jJFJCL1559hoKJVFveLh2VvDtxGGiLZV2MDbwLhOJ"
    "ATNa4iXltOqGTDxVgpWQU9ophRSulV4ztpTuzfbyTtEY6KMsu/YyQeBsywiMVZ3EcyqJrA3Fqf1lF3hTbLGQWXNVCJQFH/acOi1c"
    "Gxaue0fdLs8RhBO+QvuYhV1U+PofSpnKLNXcsKWah5JAwhWs/rQDHHZTSzA1MZXvhXPc8ySj8ByQlAYhwmUS/JAbsOQ82DujiNSC"
    "v5ZpyXjYUBEJ1jJyQnpgAUXczXbAVKphc9AOM6GYWeAQgeSir0I0RwMJvvJtZ3xnm6V/arQeo4g9XX85C1eIWgJKU8gTTew5+3Re"
    "/cs+gtnqDm4p3EiRJJ5tQ7DyZy+r44u25FgiaNYjClVBc3o2BdFdmvCT9q1xdjayOex8A4snl7DuUvdsjprwk0sfLplKN3z54mlc"
    "HSFHzFxbQhJG0GExAwn86a/4+PB+Pp600RDUoYHq0SWKR5qmmg3BBWsEaXxHS2SKggnYUVOOtetcrRkui7MqM8Zze+6z/oIS+6lv"
    "CaA6Rb3+RwAZjwBGa48NlGMk+/rNAABuSSnlwTv++e41ApPP27V/jH0y/jEa1YoieR3WSvlhH9A+Y7PqIKWKQpvVd3vzR1cdejct"
    "ZNjbdn6FwlTj1FA5DjeqvdZLwk691DLlJk9t49fBSwK/Np92oi9u7O0IApQGKxUlxOLKFhEqBzrLU1FQvpeXf/p4UZM6Pt+3vhcg"
    "Oo/eYsVRp1pYFTJYf7yoRQjqjJ8a1gFaxIV0s3GYmzESzcRJnaWIiTccAnRJYV5/2uGScF3C4+3q5HH549cYvhzI7bmkoCkhs46C"
    "1VRtOSFYXe1c2XLf8vxq9hNC6LXukn+DXnVINXNhmweHQCGDtmIhG+mCbGmyWDsVhBGJE7ORrWGnWua8sKXmNggfhqrksv7UvwLQ"
    "em62BuI4IozILJFSD0Gn3QitkrFshPiz69iSgfAV09TpERN2A7CsA1sJugs4OOKyF6CYQ6FU3ET4qmEqoPwIeE56tRuYiki7rFmu"
    "VXg8mY+HX/U6yZGwswm3q37KLL0UZZbpVIPq7N4CghuHN2i/Yf+oALimaiuyPEnTFSktuDbX8QVUbp/sRZwl5iUwRbhwxUATKfKn"
    "Ht7sl4+rF09xjr/7YpGeuYyj3u42cXrE2hMF4WskUe4gCIRhN41iXIa56Dl6ayqU6cOCZogFtZUYRq1rgTxkpxLDAFDa3QESu/f3"
    "q+fDoYEikYgSaiLd4UcYfUIGUcSlpDiwZ7B1IcmR5SwcpOtvpB2Y5QTTfAQy907bXYFYhvnUoF+Oo6Yi6qpHIFa4dRsr0hBiqc6t"
    "xw2RG2acc7nAOe9gx7wKN+SUjmH4cPDgWcLC1f4Np1MMw4dDyPT9hZP15FA2QVJxuPyEXcSIlH3S1avhTkYQRjOZl7NPURFQjzoB"
    "q9fpCGiMJnwwAoq9Q/sWCUv9oOXgShe6abiHlablPnG0VPhzUzXg9Wxi5RJAG9NUafoQNUVOumO5ejQ5x1eziycREQ6vkJGLYICD"
    "68xoGgWXHYIQO9P2mZxdTiEXAc8kdgaDnjtXVpUtY6qT85faML10lnxIs+bPXMrFwugmBCMWPdWMOPBNrHk9lUiEpzIgRTSlwcE1"
    "x6/tp52Ahb/mMcB6ZUQHnSrw0JoLpPkFLu/gvfn80luc8uDQuBfQE3wwHatg4a+5XZcYjECdAtuW/0BKCXNBrLCnpnit+nszK4wT"
    "p3gqBRMcBRihFJyykvBr+6l/m2MRSb3CL3fLlzGnWgDIrT3W4YJVuxeNlljMsX75BvnIHm2ZfplMlk+FL3WKKLDrxi7+SvXsvPxh"
    "d76/X30+MoIRw09/5283px8vfAh2hpon3Fo7TdSVsKla13oZJNBkmhim6imxgq/tpx24g2tLvQQV8hj8oPcOCEkXtJOKFAsL2l88"
    "rvkcsHcNDhfqXUmMX8+lLaRV7sAzRmMUVoLITT0g1svH1csnMamE3BY2NGJCiMwixIQoXftF8j/Vq68Qx8EA4mU1flrTEQppSBmG"
    "lQ8HmptdTGruwQKpCHwdIb6EjpBLRttT9obztDFlVDv7IBYExU8oPIWbizDImk87WhbeVgFyv/k/Q6ImJgLi+rdcZb0BkFg5sjZ6"
    "cXwB+7j2boBYcrkwCJBjmbZOj5gq6pyjhEqZ11D99X8dVfcn1+MhwSfC/RUyKkJ7wtwlv/YjXFnCGVtfUCRNswWZiSYoAjhQn6ng"
    "+p55sRvHfifxmW9ISRDERJCSAKhqKczap8dg3YkslIFYdP9/f1kD/Zncum2aulM+fD2bbgOqAe+L20yYf/3FNZ4SDHyHNkv498lQ"
    "tvuud0lNKNToekhNLHbNJC1MQK2f1OQaP66nQvXy6exTzJtfOCTJeZKF4aLGSRU3cPmtujr2rq29CfJjD2/OQz6xNLvOk0JiHXHY"
    "lO8vN+r7N3gmKLSFSyEW+iQ8dMPLN7MPX+OyVgbZ2kKG87XqXjKdFaO2/jCuDfvT6VGmMvvAYNzAZ2cgl51nbJj+KaWctQ6Lo55Z"
    "jJMbi0MOeD1Y1+LwEHAv38w+DpctyRLuq9FBHLnH2GBLGxvmJwA4pZpCjWNvHDmDntp4pnp0at0s1w3K8LxUxcs35cH+bZze0+G0"
    "pDqRqDbQ8hhoOl3IqPkliOQ/ntRhT+wVTm4haEi+ZNphm6B5MLGTa0gs+aUtbgzr5Zvyzz/FwG0cJsMsgeWm5DfFICXupiBlfvi0"
    "Jst6+QaYjpDI8JoUd5aTnNxaOhcNedNAp6nsnRRJ4UJrbuC24jvYTnK1EwV/dErzAfoX3rnIXwjXWARdZLnzFlCwdpZ3MBeQyY5v"
    "KbREYNYwvkinSZC9tR4IiXEkS/TtQDdhBdRTJzMlBQKge2FN8LX9tINx7C5yFFe+TiR3rQCx3gtK08AFyYeQ4UAPyZPDk4wvzWfv"
    "V2P5plWM/64ThnITTQm2oEuwgSc0jSnFMkWAEEZ7sG8VSApMAQWnFDtCTCN2a7X73Ccn9iKSbyDRH1PR7LH3IyE1XYEVU5IRqpvC"
    "3uHzycQ10sWbFjRj4yavQdcy9xD5sw3XMqOrafRaelIXrVeadeoYsailXveT7TjyAgFUcw60Q6y9iBEPj8s7IIPaTYMbNSmsPB9l"
    "5KkUyhj75h/aDsPhh5aec446t6t0RuykFshOgDVYHItZcRg9RAYdWXXmUUCd7FYX+5FgauWBbItEhuuxGkJysRwhOXYNd4ApF/T5"
    "yEOMu4uatIwnJhnNU0Ycdzs+KlG5qfKrhpAcScgZcBYYhr8eQnLzaee4uw/lyXg2HUfY8RyZXmo7nlPUBfB3a4rsi6gs38EEMpzM"
    "iz171pG6oChIgkzsDWGuY9/W+Fpi2Uc7jQD2jwr/ajwlDV1tWP2i0bsKc40OF6SqO9jHmBjZmpFtUB2kK5SAkelBXZARApgCCnSV"
    "pUnu2kWrSR61ole5eTwNnRrrpZvNO48nQ4KIdhvEUKTmCUNDs+HaCsscmtijohy2BTFYON4TU6+EvUNFhy5NqkqRwCgyvNtt2qg6"
    "ixHkkapH51vl8RVkmX7YK79gTv96zrHz0RZL2VYf+5ZrAHfZt2DyNhcKVgbbZeSyQI7K8LT0wMA6clkC07DNxjmCYo+IBDUAjd2c"
    "o4YM2/X3b3YJFg4GSXZ/QgjP2X61C5C7rWr3qHp40tYf4mlOeYeGgOUKAX6BS56pgvXVzAz6u+3I4VUv0lFG8K7CaGmMvLahWPyn"
    "x9NkOV+xBWanQAIiCG8PG/YPE4nA1/bTTtjSDQefToEwYGdSvorRssboYBsSCAMDpYbaGzWEUqg8xz0BcZqz45ox98Gp5dxlaZaO"
    "GFmC1huqFKKHt9qtW7lBQQM+l/WE/st9oH+MqzB3GIx1khdhDsS64pmoIx1eGA7/yVSYhwUJB9eqm6GeHmWW+9KXtdRCUIq0dsjE"
    "muEEbORutVMqc5lniFO39aFhDnj42n7asc1cE/fVFcBromyzAkK9rTBdmN0QbQJaYGkR2X/dLdwC39fxDCtMGKsc4DZm/gXcHvBq"
    "0Ln3JOpoETQcNvG+4iRs5n0104ri4m6J8AIdcunn2Bh6c80e+Br3uBZQJOfA63vR9TflF3l4VH40T6COoBMiwfSmGhzJZQxS7zpc"
    "P7z6bmHgNZD9XwNjjxeALnqs8gZj3zGuvGDwq6/lD8Pl1WSSCw/6h7ENgr9eEsFggn3e/FQru5hkVd5SD8b8Pg4KDW7FDOmiy2DP"
    "kfw2+Djj6IhlVjnJaK0S7YLuV8daD/W9jGmj9YFI2jAXI35tP+2cdNeSfv0E0tonw2MaeZI6wjF5klG3vUGAEOs9GAkzH09MBw2X"
    "1LXzGSwWH46zufh2fogEAVhdFPSicLjUOd/cLW+mE05vWmQLihObg54WPg6Pe0KkrwEbGaOaiWVTTdan6FXNJNlC+hUuXz+ZP/hk"
    "Ev28A7oH1cwQgHNhm8+ASsawhxlcVvCgM5CvoVJJFBMEA+p6vuJKVF8903hIsNht3J5Qz+xwAyFayFns8+EJKpFwT6ZAooUXsukF"
    "yP9F1aDuHs1+BkJztMTufWtp7EUqihGyGQ2z571WcHCzi+3ZBUB0s5r+IYNCm/pv6FaiKkrFAMc+TMmPbbJAGSdbc1jrNDOPvZEk"
    "piijRP1pB4vrWno/HEeqlmQeCjeMTLEo3HxJaUDsE+6JbtytaD2biPb2JiCG8Xkb7D2UM9Ej1Ays/x4aTAuDJcKvJNPAOsG0DMFj"
    "AqXHeyiY7acdBkH32T/bnn34GmPgA+qg9fCgHqWHQXCpyKtjl2PvLKLyZiY+RNPu3W0jdtkIqRCG0gi6WIuug0fV5KzTxrfs2wjE"
    "bzkdgk8/78gXCE8w+wzS1nFY2twpugPapB59MqqEeoj8uP2pLtqAwBm1PNij4PLY/q0vncW9t/VsO9KQQg7GJl7Wpz+uiGIpwuqp"
    "Pryvs4LYqa0iVMsw8JeFKWboGmGSVPvCcVFBMc1pX6lwE8arM6EU2kXCpH17KhAaE0p0hN2UJ6t6tlvu7pVvh1tROsEcXRtnVv2c"
    "1WGu3YXIjJ2vEBMxMVG4MAlXxvaGCjQrcn2ACmvpVIB/B7lxhjMAKMQIJHpTKeS69RHx/kl7aBb6pM2ge+u7fkzKpJ3I+Xi4ZJFK"
    "hI97DTOLCIbF+dSm7JS6w7+/usJLZPeoundscaoQqwdfDiHKC6rlQ03Mvrwtf3yHidJOATaYt2Tdcx/4tY+qZNURm3oOpWAFs7LO"
    "fcXyWfNph+7b5W88+6l8/lP1/UVMtiv3GL3C2IlGQCNMOLVI/gLe7Ys9Y7SlheFxC2e7oDPEscGurfHYeKroH0AgLw5JnHuEqeFS"
    "kpUxoxVZPury2vbyovVQlppIYX/ON0dMySru+TRzr6cPRzHZpNzlbMkTRXmYUMscV7fXln7PH8BPONvYOdy1jHVhHjLD/F9kXXm3"
    "cSjk+7htwT9EyAEGTUJ97CRstkwcnQiOlLI10kf1lokr3kX6uKHGD+9n07g90D72eaLCscZmE0QQNoTXCXqHyQUdyijfeMWv7yli"
    "D/RsAUWJfkmRaBdH+1/RHuDoWrd7AHQB9rcj7lsNIOBFTInmwuVxF24rVmC9TZXn3focbjRW+pDS1xusR4m+E+Ep4cCGlQGmFO9d"
    "xnwe6tVApM1MSlVwbhjvILZLar3lXNlPfa/JI5ut0amRQrl5InM3zyTDGB2zU0ld7EUnFwJFFz6IlqNh6R1ZtLavw/GmX2cfT5a4"
    "Ljp/qQ1NkQkonAfiWsBZ2VAUCucZGUGsK92bgLLkIV12zNy9EXD4MTuicHVMDEHiBnYEOoIREOBAY/PxkcGooY4Fu84yQ2yxXpYZ"
    "nA5qY7h0jZvYGALInQBYkqaWFozcGPbTjsnomuafn8YAgyFQ314VBUVZrJDzDfbu8I1hSx7APcU+IflbJ4CcDRfldZq7eAH0DtOn"
    "1ZFRXuZbt5u/oichQV0FdtSbWXGWwdmXUkNdLK51n64NUMCZT33jQLrBoM9R0iXSpiBqyyAFuCvh0oJ0BY9xacdP5/dMYA10CLGo"
    "kzOMtgf9WS8R0Hm+sV9r9Gc9HbDPE4hdRdlXmPN2tOiDMTUpoTCXjAS55hBEbj4c2RiOITLZLZ8giJ6JEHCn/7ebISHvErNZXSQ3"
    "dwvaNKLxg3ZWb1IfhruJA1NPoFR5CpTt8HT2SdHD1+bTzhXpmlVfTuJCF8yT/BNYwBvW+gFUTRij1yvQMz9GqlJAVGLfDEg9G6Ex"
    "GCX107bkcJ8KrUdYB+up/CC8KLzyPaJ/OPqNrLydT3ClwB5KYRjgTAWLH4wmkPm040u7K/+vT6uHP813gXKmOp3Ovxuej8g9VEee"
    "KEr40Xh/CJC4gV8N6Cq7D/IRArV8RzgA9ohtvHW1KV/LjplyqzNbE9gTFwMH2/XMV+1gS0ON0ONpNea07BIkuYov87vT8iyGIYs5"
    "DFmQg+vJqCjq9qczKo/G1QmC7GafLqpn9xtDmixZKcQAXhHop8uiQMGyuH/130TtwZ/ieK5Dh3oclN3FRsgOcbmusxGGZ173YJy4"
    "FgtPCFASrYTPxYg81pP94KfyLaD8YzIdaAg2ASMCi1zX9Yil6nrmT6/APoFwIeMjFpLWWNhEPTSDR9q6XX7Zrb5MQLfwzycdFbPc"
    "CClepwZ0foXMtejcCTP1KG24+fd1B5jr6Zc6z0Vhgot5X25e1p92QOuO8Tt/8Gk2PYowhzJHXUEnLMwS3qRy8qVSOfP9fSeCoI3X"
    "HzRWsDdU6kb2JOaBTWIFx85VlzX42xg0C/K3Nk5Elvfigge4YiEM72SveoCuGCskLVKBXaHMfU8PuCMhkqYroVFmuftYPPhUTe6C"
    "kv3u6xjP1sFZQYAvbKjnwJGtqPyXWw5humEoA6aAkQMLfXIXbqKarjIc3Ao3AlbG9Gg2PTL17GLrNuxx+OrwDgicTC6rz+/K8wvQ"
    "vP/hvNyZVF/BhutcaiAoH1RupVvY6v7pd68B/nt5Uu1eze9tk+45CRKzk7sRPwCWSwO9VVFIheaewP8lSjc4rz/tUC870VO7JHuT"
    "8g0Glf5te/3b9rrZ9oI8Tru96scr5lH10nVMrPdR1XmG1ffhF1XkAxjYsZM9CTaXnv0GLoSLuJ8ffAsBLZzX8uP2ospqnMMGKRpm"
    "CWukpG9YWF33bIsV+I75pdBB2d64tpEdW0iKwNMOl1gpGPymi6oLg7c2shV5b1E1yAf51TfuXf3kqNo9iai+EU6NnbYVluHqG0h8"
    "x1TUu3Uzplt4qsxPgNXLg2w3y7Q2/QmoL1G4yE+paqERERjcAzh0ag8IsuAS2MRWLwOH8wtcFRxrLqC4orfgxn7awYq71+o/Pyrf"
    "DAdrykQ7tPcgGEIpL2eY6BARMnDlk8f1nYqdMneqv1KqUDRvhdbu3dnlk+IFfbF6GMAb4My88Nd4AnHCvYlNsg3mrnCZQAoQqyOu"
    "WBJutlBr8TmS8WEp4hRuQiRlS9MgSXxEY/hTW9uSI1OBf2mTJW44bOKUFarHUxJrOGU4t3CJSoQU5IbHIO29b6XugGRdzCHgjncm"
    "MRGBLBH4ujYFjxDQohSOFY9SOIYI0DFsS0PQlhfXJI5DMKNwW83I8F5VoG9dt05mjXFkxFqbXP0CYGi++lWvlY4FyEUjXSRTC5SO"
    "7aedG8Ap0DDMMFFn37OuwjmxNfDWcCoShF2ijdW8oECAGU9EvpoQhuzM6NmXcvou5hw51EpFwiF4RTPbLqe11ZLPNh3ELD1nIzSC"
    "l+aybQYLDCNAB1N0zqoqMEIdPmYkjZOdho1YrzVlMOcyxZoDq8BIV4vaTztZD4fcGCb5x+HsWsLIEDkpD9J4hRADERBcaG5CwcEJ"
    "Cq6Z/qH5AhpPy1mv15prrNcuZaMWiqo9waH35VI2COO284sWqQWb9hA2NsZrt2wY+ZXajVCdxOBLBPAmtES3EGSlGPZZKoI6BgQd"
    "/mw6Bo1dcwUACzO4LlnagfALDTGOoRT7bZvmzwDF+2EfEXtQhkoWXuAoiYOPY95IDKieRQH0frDS0tCEhEkj8GvzaaeyzDepq9Np"
    "DKQI6FI8Kijq+l8DO0yedmGVN6WH8cZvKR/Z1m3zx63o27Uwo/sBTSvTQx+1udeipZXhpkJN0OKcbW1557XgXo58PInBpMgEldxq"
    "FEJe9BSnyUHF0A2Sr/yyC9yQRqDJivOgBU54RaYrwTWxHVvtmnj3LB4FZwoPvo2pzZcePQOysRHkyBTN9ELOvJ3zpt74vC2b4pp3"
    "BK+5kggciuXka9vHlh1kjyZVr3DcxCHCWdjMITLzCnzHBccwkaZdmYYaueB+mCiVbphofAjk0T9+LQ+Gl0jLJHPYWfJEh3VuDY8Y"
    "VW5OUKlBbz5vm0sRuwZrXxhyBjfxYuSWw4eLZFOBrqY9TGp6NdEiNAXaCQagb1z1JxKbNmYt60lvkKSxRHrjxeOakWz6bjbda1Jn"
    "2SgPUZwuaqUZnSU2xfvZq2zCSq5rD5cuH76tzra3BMkq3WE37Rq4MCcbsXbsLGP5Ud7SXuJAeyqVcr8cxezWZksclQ+Hl1WLRGJt"
    "aqss1xM9MP5UfORwfFK9eIopVfwJT53MggnV6LZOTY4VgZOud5NK0rvBERNrLygyrIInmSu4trKgIaQRc8hmGoXRYnHQ8DopTmf9"
    "/zwcqZElintgMyBjXi8jBcaMSRif4vkAAKXt6JrV7wwwu53YajeGaghpUppqHlTvIqp5QNdjqWqeD0dQ2nFwuCWvKzJkQZ9xQYuz"
    "6ePq81Ndizxs3W7+ijsgJfECcy2vLoP+gvsBvbqkj4kztCFLJ0sVKChp4HdbLAJhKn9S1uEadlX7YHO8PC+nT2LKvdL24BUJT/tD"
    "jDHSviF9q3t3nRCjBu64G8ll1c0ZAb/r1nNPhBHHTUUYKQNqnTJaLEMmOomeY9bPR5d1zF28EJtN8Bbw4rtHkNO6GO75iEQ5no9O"
    "NGKtqUe4oIj8Fzycp1MrSWe6aXTUsOjPS7aFQs/D24aAwfhtW/BiVA7COQLS67EzsJFtYOdUCFlAeUKaKvR9el5g+2kHMem9wED3"
    "E+PveO4Owa6F7g7EQmPcnZ231t2ZTfdmHz+jDlDeZQgBd4fMjvd5O+5lvg52KBfOO74ALF5EDE8lDLPgC8ppsTCAQaQxNK9At+my"
    "OzXdQD0TyFwfbmnOEQrUOTO9v+oOxyRpuFZ1YeDWbWCCPTi803xVPZ9WHy5mn96X04Pq2RQm4MVjHywo87QIAuz7G6HIp5hyIfc9"
    "/KEkoUfGkpytOt0KiwUkoqwo6oQQfVrxa/tp59J2zbrJk+pljEyImxnUCQ9DT+29Qkb6+u9TsOF/uMK7GntnHKaQPRfREv4Ed7Lg"
    "xagjEAHWDZEYsAOmXGVBErpAVn7V8l31rApZcCDmBSVEVLvrva152tG+RBBcs/6XMel2nXDIcTlpQdVLhlgsRYZY3v/i1lz0kCHy"
    "IhtE8swBgBV0lyS/yUH1JY1chOgEiPGWrDAj+fzQEAN2lxhy3pZD+cVjMNDwXEHvEMaAl4dnuurhZL2BpgGadnAOQYoPR2gdZ8IY"
    "20FjGEdNXK6kNN5ajGGEM9cRKJ6JBeTM5tNOAsV9sQ+35w8+RTzXqcfLLwiBa6y6ogQ4iIq1+WQXmJiNAIeFCLZsKMH3L9VsEPAa"
    "u7n6ZLhfIea6GIeP4GKIjahrBxWmEqydIJJTmrqywsmp+fETS7Zre9YwHi/i6yWbwHBegSaVWz+YI6w/aKPi6IiEl/sErTWUa2Yv"
    "Aw4coQzyDw2UsC4vUnqYTzv4P/dpOnxa7R1B8u/Ht+XL4XBbYa2SBSyzBi1BisUPECwY79UAJuyp5Z0KSFkt0ZgRNILwLpfWMsZX"
    "0Bc/IO5VOwPkod0cCN8EGXLFrLBRn96J1TqATzvECW7K5/ApkPMdnJuCnwhMg/DSqwYxTLAmQNnUMqwJ1auv1aEJEE1e23Bv3jU2"
    "ucwwdHadJ2ryGpgR/vVkPn5ihhPJq9D+9SaiaThXtnRagFCC3zqBM7XTRLi8Ht54/XxU3AhLAlwfxtDPrGA/7RCVpYGdE8NVhnWw"
    "C+rszF+vxHIMlhCusIJ4h5DsQ6PMiqJ5mwa3UXDJsJfEkknaQxE+ec4NcrJSX5vmCIdCeUTWYdhDzaoSfp37mWig5vj4ytekkC2z"
    "WXwz7ukSnOX2fubXiG2oJbODpuzeTWEeGqqajHGG8O2U9/Drw9f20w4HmHfK3sHGvoTsd4SF5pfIpVART5loeSS59cMTQNYbIBik"
    "2Q3rg4EQEetj+0O8n9i79QX+QCnXm87n0+rMgtcWyj25uWyk2ifUniButKzZs3uElurhVpYZrcWltJ4A73d6VEf9WLF123wREnkq"
    "SKQ9lz1IXSXJ6iWeyKXhKD3GDgiN5irNbUKtWCzslHd0kVnuuTvvYt4rlTh8enmiMbBOhNKLIWXhbSgd0tc/vjNEQOcArEWy7Zz1"
    "uJA0rSV2bH0HiCm3+OHFbowwYpaknjYWAb7KCkET/fjA5OcgUWutM4h1w0WEfTKVevk1sDPIlywAOwfaNH9mBXCZQhhaMOKC4yNe"
    "HplSBwYU8lxqypVQyNhZFECuBuST0O2e5we+Np92wO1u8ulFlIWnE+0AV4tEynD2Cf9uiveEWBvTFYO1vKqOsLSBq9TAuIYtb9uE"
    "+ck2BInFjq2hRUbaGjhEasVhwJuxNcwU4gpaGnI5YLG716MXIDh+U+5ECcZjEuwPjehpOHZt78cokdv2fgQVHwMzEGlKFcnbrhD3"
    "Y8aAZdD+Q6wPCMcvj8f6z//T/wuxzJHI"
)


def get_beach_observatories() -> tuple[Observatory, ...]:
    """API 상세 id 36의 주소 포함 해수욕장 관측소 번들 목록을 반환합니다."""

    return BEACH_OBSERVATORIES


def get_builtin_observatory_list(api_id: str = BEACH_OPENAPI_ID) -> tuple[Observatory, ...]:
    """KHOA 포털 OpenAPI 상세 id에 맞는 관측소 번들 목록을 반환합니다."""

    if str(api_id) != BEACH_OPENAPI_ID:
        raise KeyError(f"no bundled KHOA observatory list for OpenAPI detail id {api_id!r}")
    return BEACH_OBSERVATORIES


def fetch_openapi_info(
    api_id: str | int,
    *,
    session: PortalSessionLike | None = None,
    timeout: float = 10.0,
    url: str = KHOA_OPENAPI_INFO_URL,
) -> dict[str, Any]:
    """비표준 AJAX 엔드포인트에서 KHOA 포털 OpenAPI 상세 JSON을 가져옵니다."""

    portal_session = session or cast(PortalSessionLike, requests.Session())
    text_id = str(api_id)
    response = portal_session.post(
        url,
        data={"id": text_id},
        headers={
            "X-Requested-With": "XMLHttpRequest",
            "Referer": f"{KHOA_OPENAPI_DETAIL_URL}?id={text_id}",
        },
        timeout=timeout,
    )
    _raise_for_portal_status(response, api_id=text_id)
    payload = _decode_portal_json(response, api_id=text_id)
    if not isinstance(payload, Mapping):
        raise KhoaParseError(
            "KHOA portal OpenAPI info response root was not an object",
            endpoint=KHOA_OPENAPI_INFO_URL,
            failure_kind="parse",
        )
    return dict(payload)


def fetch_observatory_list(
    api_id: str | int = BEACH_OPENAPI_ID,
    *,
    session: PortalSessionLike | None = None,
    timeout: float = 10.0,
    include_address: bool = False,
    vworld_client: VworldReverseGeocoderLike | None = None,
    vworld_api_key: str | None = None,
    vworld_domain: str | None = None,
    vworld_env_file: str | PathLike[str] | None = None,
) -> tuple[Observatory, ...]:
    """KHOA 비표준 OpenAPI 상세 엔드포인트에서 관측소 목록을 가져옵니다."""

    payload = fetch_openapi_info(api_id, session=session, timeout=timeout)
    rows = payload.get("observatoryList")
    if not isinstance(rows, list):
        raise KhoaParseError(
            "KHOA portal OpenAPI info response did not contain observatoryList",
            endpoint=KHOA_OPENAPI_INFO_URL,
            failure_kind="parse",
        )
    observatories = _parse_observatories(rows)
    if not include_address:
        return observatories
    return enrich_observatory_addresses(
        observatories,
        vworld_client=vworld_client,
        vworld_api_key=vworld_api_key,
        vworld_domain=vworld_domain,
        vworld_env_file=vworld_env_file,
        timeout=timeout,
    )


def fetch_beach_observatories(
    *,
    session: PortalSessionLike | None = None,
    timeout: float = 10.0,
    include_address: bool = False,
    vworld_client: VworldReverseGeocoderLike | None = None,
    vworld_api_key: str | None = None,
    vworld_domain: str | None = None,
    vworld_env_file: str | PathLike[str] | None = None,
) -> tuple[Observatory, ...]:
    """KHOA OpenAPI 상세 id 36의 live 해수욕장 관측소 목록을 가져옵니다."""

    return fetch_observatory_list(
        BEACH_OPENAPI_ID,
        session=session,
        timeout=timeout,
        include_address=include_address,
        vworld_client=vworld_client,
        vworld_api_key=vworld_api_key,
        vworld_domain=vworld_domain,
        vworld_env_file=vworld_env_file,
    )


def enrich_observatory_addresses(
    observatories: tuple[Observatory, ...],
    *,
    vworld_client: VworldReverseGeocoderLike | None = None,
    vworld_api_key: str | None = None,
    vworld_domain: str | None = None,
    vworld_env_file: str | PathLike[str] | None = None,
    timeout: float = 10.0,
    search_offsets_degrees: tuple[float, ...] = DEFAULT_ADDRESS_SEARCH_OFFSETS_DEGREES,
    require_road_address: bool = True,
) -> tuple[Observatory, ...]:
    """VWorld 역지오코딩 결과를 관측소 목록에 붙입니다."""

    client = _resolve_vworld_client(
        vworld_client,
        vworld_api_key=vworld_api_key,
        vworld_domain=vworld_domain,
        vworld_env_file=vworld_env_file,
        timeout=timeout,
    )
    return tuple(
        observatory.model_copy(
            update=_lookup_vworld_address_fields(
                client,
                observatory,
                search_offsets_degrees=search_offsets_degrees,
                require_road_address=require_road_address,
            )
        )
        for observatory in observatories
    )


def _resolve_vworld_client(
    vworld_client: VworldReverseGeocoderLike | None,
    *,
    vworld_api_key: str | None,
    vworld_domain: str | None,
    vworld_env_file: str | PathLike[str] | None,
    timeout: float,
) -> VworldReverseGeocoderLike:
    if vworld_client is not None:
        return vworld_client
    try:
        module = importlib.import_module("vworld")
    except ModuleNotFoundError as exc:
        raise KhoaRequestError(
            "주소 보강에는 python-vworld-api 패키지가 필요합니다.",
            endpoint="https://api.vworld.kr/req/address",
            failure_kind="request",
            retryable=False,
        ) from exc

    client_class = cast(Any, module).VworldClient
    kwargs: dict[str, Any] = {"timeout": timeout}
    if vworld_api_key is not None:
        kwargs["api_key"] = vworld_api_key
    if vworld_domain is not None:
        kwargs["domain"] = vworld_domain
    if vworld_env_file is not None:
        return cast(
            VworldReverseGeocoderLike,
            client_class.from_env_file(vworld_env_file, **kwargs),
        )
    return cast(VworldReverseGeocoderLike, client_class(**kwargs))


def _lookup_vworld_address_fields(
    client: VworldReverseGeocoderLike,
    observatory: Observatory,
    *,
    search_offsets_degrees: tuple[float, ...],
    require_road_address: bool,
) -> dict[str, Any]:
    merged: dict[str, Any] = {}
    first_match: tuple[float, float, float, str] | None = None
    found_parcel = False
    found_road = False

    for latitude, longitude, distance_m, match_type in _nearby_lookup_points(
        observatory.latitude,
        observatory.longitude,
        search_offsets_degrees,
    ):
        try:
            payload = client.reverse_geocode_latlon(
                latitude,
                longitude,
                type="both",
                zipcode=True,
                simple=False,
            )
        except Exception as exc:
            if _is_vworld_not_found(exc):
                continue
            raise KhoaRequestError(
                f"VWorld 역지오코딩 호출 실패: {observatory.id} {observatory.name}",
                endpoint="https://api.vworld.kr/req/address",
                failure_kind="request",
                retryable=True,
            ) from exc

        fields = _extract_vworld_address_fields(payload)
        if fields:
            if first_match is None:
                first_match = (latitude, longitude, distance_m, match_type)
            if not found_parcel and (
                fields.get("legal_dong_code") or fields.get("parcel_address")
            ):
                _copy_missing(
                    merged,
                    fields,
                    ("legal_dong_code", "parcel_address", "zipcode", "detail_address"),
                )
                found_parcel = True
            if not found_road and (
                fields.get("road_address_code") or fields.get("road_address")
            ):
                _copy_missing(
                    merged,
                    fields,
                    (
                        "road_address_code",
                        "road_name_code",
                        "road_address",
                        "zipcode",
                        "detail_address",
                    ),
                )
                found_road = True
            if found_parcel and (found_road or not require_road_address):
                break

    if merged and first_match is not None:
        latitude, longitude, distance_m, match_type = first_match
        return {
            "legal_dong_code": cast(str | None, merged.get("legal_dong_code")),
            "road_address_code": cast(str | None, merged.get("road_address_code")),
            "road_name_code": cast(str | None, merged.get("road_name_code")),
            "parcel_address": cast(str | None, merged.get("parcel_address")),
            "road_address": cast(str | None, merged.get("road_address")),
            "detail_address": cast(str | None, merged.get("detail_address")),
            "zipcode": cast(str | None, merged.get("zipcode")),
            "address_latitude": latitude,
            "address_longitude": longitude,
            "address_distance_m": round(distance_m, 3),
            "address_match_type": match_type,
            "address_source": "vworld",
        }

    return {"address_match_type": "not_found", "address_source": "vworld"}


def _extract_vworld_address_fields(payload: Mapping[str, Any]) -> dict[str, Any]:
    items = _vworld_result_items(payload)
    parcel = _find_vworld_result(items, "parcel")
    road = _find_vworld_result(items, "road")
    primary = parcel or road
    parcel_structure = _structure(parcel)
    road_structure = _structure(road)
    primary_structure = _structure(primary)
    road_name_number = _road_name_number(road, road_structure)
    road_admin_code = _road_admin_code(road, road_structure, parcel_structure)
    road_address_code = _road_address_management_code(
        road_admin_code,
        road_name_number,
        road,
        road_structure,
    )

    fields = {
        "legal_dong_code": _first_text(
            _field(parcel_structure, "level4LC"),
            _field(parcel_structure, "legalDongCode"),
            _field(parcel_structure, "bjdCode"),
            _field(parcel, "legal_dong_code"),
            _field(parcel, "legalDongCode"),
            _field(parcel, "bjdCode"),
        ),
        "road_address_code": road_address_code,
        "road_name_code": _road_name_code(road_admin_code, road_name_number),
        "parcel_address": _field(parcel, "text"),
        "road_address": _field(road, "text"),
        "detail_address": _first_text(
            _field(parcel_structure, "detail"),
            _field(primary_structure, "detail"),
            _field(road_structure, "detail"),
            _field(primary, "detail"),
        ),
        "zipcode": _first_text(_field(parcel, "zipcode"), _field(road, "zipcode")),
    }
    return {key: value for key, value in fields.items() if value is not None}


def _vworld_result_items(payload: Mapping[str, Any]) -> tuple[Mapping[str, Any], ...]:
    response = _as_mapping(payload.get("response"))
    result = response.get("result") if response is not None else payload.get("result")
    if result is None:
        return ()
    if isinstance(result, list):
        return tuple(item for item in result if isinstance(item, Mapping))
    if isinstance(result, Mapping):
        items = result.get("items")
        if isinstance(items, list):
            return tuple(item for item in items if isinstance(item, Mapping))
        item = result.get("item")
        if isinstance(item, list):
            return tuple(value for value in item if isinstance(value, Mapping))
        if isinstance(item, Mapping):
            return (item,)
        return (result,)
    return ()


def _find_vworld_result(
    items: tuple[Mapping[str, Any], ...],
    result_type: str,
) -> Mapping[str, Any] | None:
    for item in items:
        item_type = _field(item, "type")
        if item_type is not None and item_type.lower() == result_type:
            return item
    return None


def _copy_missing(
    target: dict[str, Any],
    source: Mapping[str, Any],
    keys: tuple[str, ...],
) -> None:
    for key in keys:
        if key not in target and source.get(key) is not None:
            target[key] = source[key]


def _road_admin_code(
    road: Mapping[str, Any] | None,
    road_structure: Mapping[str, Any],
    parcel_structure: Mapping[str, Any],
) -> str | None:
    return _first_text(
        _field(road_structure, "level4AC"),
        _field(road_structure, "admCd"),
        _field(road_structure, "admCode"),
        _field(road, "admCd"),
        _field(road, "admCode"),
        _field(parcel_structure, "level4LC"),
    )


def _road_name_number(
    road: Mapping[str, Any] | None,
    road_structure: Mapping[str, Any],
) -> str | None:
    value = _first_text(
        _field(road_structure, "roadCode"),
        _field(road_structure, "roadCd"),
        _field(road_structure, "rnMgtSn"),
        _field(road_structure, "level4LC"),
        _field(road, "roadCode"),
        _field(road, "roadCd"),
        _field(road, "rnMgtSn"),
    )
    if value is None:
        return None
    digits = "".join(char for char in value if char.isdigit())
    if len(digits) == 12:
        return digits[-7:]
    if len(digits) == 7:
        return digits
    return None


def _road_name_code(admin_code: str | None, road_name_number: str | None) -> str | None:
    if admin_code is None or road_name_number is None:
        return None
    digits = "".join(char for char in admin_code if char.isdigit())
    if len(digits) < 5:
        return None
    return f"{digits[:5]}{road_name_number}"


def _road_address_management_code(
    admin_code: str | None,
    road_name_number: str | None,
    road: Mapping[str, Any] | None,
    road_structure: Mapping[str, Any],
) -> str | None:
    if admin_code is None or road_name_number is None:
        return None
    admin_digits = "".join(char for char in admin_code if char.isdigit())
    if len(admin_digits) < 8:
        return None
    building_main, building_sub = _road_building_numbers(road, road_structure)
    if building_main is None:
        return None
    location_code = _road_location_code(road, road_structure)
    return (
        f"{admin_digits[:8]}"
        f"{road_name_number}"
        f"{location_code}"
        f"{building_main:05d}"
        f"{building_sub:05d}"
    )


def _road_building_numbers(
    road: Mapping[str, Any] | None,
    road_structure: Mapping[str, Any],
) -> tuple[int | None, int]:
    raw_number = _first_text(
        _field(road_structure, "level5"),
        _field(road_structure, "buldMnnm"),
        _field(road_structure, "buldSlno"),
        _field(road, "buildingNumber"),
    )
    match = _parse_building_number(raw_number)
    if match is None:
        match = _parse_building_number(_field(road, "text"))
    if match is None:
        return None, 0
    return match


def _parse_building_number(value: str | None) -> tuple[int, int] | None:
    if value is None:
        return None
    matches = _ROAD_BUILDING_NUMBER_RE.findall(value)
    if not matches:
        return None
    main, sub = matches[-1]
    return int(main), int(sub or "0")


def _road_location_code(
    road: Mapping[str, Any] | None,
    road_structure: Mapping[str, Any],
) -> str:
    value = _first_text(
        _field(road_structure, "udrtYn"),
        _field(road_structure, "undergroundYn"),
        _field(road_structure, "buildingLocationCode"),
        _field(road, "udrtYn"),
    )
    if value in {"1", "3", "4"}:
        return value
    if value is not None and value.upper() in {"Y", "TRUE"}:
        return "1"
    road_text = _field(road, "text")
    return "1" if road_text is not None and "지하" in road_text else "0"


def _structure(item: Mapping[str, Any] | None) -> Mapping[str, Any]:
    if item is None:
        return {}
    structure = item.get("structure")
    return structure if isinstance(structure, Mapping) else {}


def _as_mapping(value: Any) -> Mapping[str, Any] | None:
    return value if isinstance(value, Mapping) else None


def _field(mapping: Mapping[str, Any] | None, key: str) -> str | None:
    if mapping is None:
        return None
    value = mapping.get(key)
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _first_text(*values: object) -> str | None:
    for value in values:
        if value is None:
            continue
        text = str(value).strip()
        if text:
            return text
    return None


def _nearby_lookup_points(
    latitude: float,
    longitude: float,
    offsets_degrees: tuple[float, ...],
) -> tuple[tuple[float, float, float, str], ...]:
    points: list[tuple[float, float, float, str]] = []
    seen: set[tuple[float, float]] = set()
    for offset in offsets_degrees:
        if offset < 0:
            continue
        candidates = (
            ((0.0, 0.0),)
            if offset == 0
            else (
                (offset, 0.0),
                (-offset, 0.0),
                (0.0, offset),
                (0.0, -offset),
                (offset, offset),
                (offset, -offset),
                (-offset, offset),
                (-offset, -offset),
            )
        )
        ring: list[tuple[float, float, float, str]] = []
        for lat_delta, lon_delta in candidates:
            lat = latitude + lat_delta
            lon = longitude + lon_delta
            key = (round(lat, 7), round(lon, 7))
            if key in seen:
                continue
            seen.add(key)
            distance_m = _distance_m(latitude, longitude, lat, lon)
            match_type = "exact" if distance_m == 0 else "nearby"
            ring.append((lat, lon, distance_m, match_type))
        points.extend(sorted(ring, key=lambda item: item[1]))
    return tuple(points)


def _distance_m(
    latitude: float,
    longitude: float,
    target_latitude: float,
    target_longitude: float,
) -> float:
    """두 WGS84 좌표 사이의 근사 거리를 미터 단위로 계산합니다."""

    radius_m = 6_371_008.8
    lat1 = math.radians(latitude)
    lat2 = math.radians(target_latitude)
    delta_lat = lat2 - lat1
    delta_lon = math.radians(target_longitude - longitude)
    haversine = (
        math.sin(delta_lat / 2) ** 2
        + math.cos(lat1) * math.cos(lat2) * math.sin(delta_lon / 2) ** 2
    )
    return 2 * radius_m * math.asin(math.sqrt(haversine))


def _is_vworld_not_found(exc: Exception) -> bool:
    return exc.__class__.__name__ == "VworldNoDataError" or "NOT_FOUND" in str(exc)


def _decode_portal_json(response: PortalResponseLike, *, api_id: str) -> Any:
    try:
        if response.content:
            return json.loads(response.content.decode("utf-8"))
        return response.json()
    except (UnicodeDecodeError, ValueError) as exc:
        raise KhoaParseError(
            f"KHOA portal OpenAPI info {api_id} was not valid JSON",
            endpoint=KHOA_OPENAPI_INFO_URL,
            failure_kind="parse",
        ) from exc


def _raise_for_portal_status(response: PortalResponseLike, *, api_id: str) -> None:
    status = response.status_code
    text = response.text[:300]
    if 400 <= status < 500:
        raise KhoaRequestError(
            f"KHOA portal OpenAPI info {api_id} returned HTTP {status}: {text}",
            endpoint=KHOA_OPENAPI_INFO_URL,
            status_code=status,
            failure_kind="request",
            retryable=False,
        )
    if 500 <= status < 600:
        raise KhoaServerError(
            f"KHOA portal OpenAPI info {api_id} returned HTTP {status}: {text}",
            endpoint=KHOA_OPENAPI_INFO_URL,
            status_code=status,
            failure_kind="server",
            retryable=True,
        )


def _parse_observatories(rows: list[Any]) -> tuple[Observatory, ...]:
    observatories: list[Observatory] = []
    for row in rows:
        if not isinstance(row, Mapping):
            raise KhoaParseError(
                "KHOA portal observatory row was not an object",
                endpoint=KHOA_OPENAPI_INFO_URL,
                failure_kind="parse",
            )
        try:
            observatories.append(Observatory.from_raw(row))
        except (KeyError, ValueError) as exc:
            raise KhoaParseError(
                "KHOA portal observatory row was missing required fields",
                endpoint=KHOA_OPENAPI_INFO_URL,
                failure_kind="parse",
            ) from exc
    return tuple(observatories)


def _load_embedded_beach_observatories() -> tuple[Observatory, ...]:
    raw = zlib.decompress(base64.b64decode(_BEACH_OBSERVATORIES_ZLIB_B64)).decode("utf-8")
    payload = json.loads(raw)
    if not isinstance(payload, list):
        raise RuntimeError("embedded KHOA beach observatory payload must be a list")
    return _parse_observatories(payload)


BEACH_OBSERVATORIES: Final[tuple[Observatory, ...]] = _load_embedded_beach_observatories()
BEACH_OBSERVATORY_COUNT: Final = len(BEACH_OBSERVATORIES)
